{
 "title": "DropCopy RiskServer Recon",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Matched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DropCopyRiskServer_recon",
     "select": [
      [
       { "params": [ "DropCopyRiskServer_Matched" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "14095 exception count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DropCopyRiskServer_recon",
     "select": [
      [
       {
        "params": [
         "DropCopyRiskServer_TaniusException"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HexMissing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DropCopyRiskServer_recon_run",
     "select": [
      [
       {
        "params": [
         "DropCopyRiskServer_HexFillMissing"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Other Skipped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "Skipped Short",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DropCopyRiskServer_recon_run",
     "select": [
      [
       {
        "params": [
         "DropCopyRiskServer_SkippedShort"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Skipped Invalid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DropCopyRiskServer_recon",
     "select": [
      [
       {
        "params": [
         "DropCopyRiskServer_SkippedInvalid"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PositionMismatch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "Matched",
     "measurement": "DropCopyRiskServer_position_recon",
     "select": [
      [
       { "params": [ "DropCopyRiskServer_PosMatched" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Mismatch",
     "measurement": "DropCopyRiskServer_position_recon",
     "select": [
      [
       { "params": [ "DropCopyRiskServer_PosMismatch" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Missing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "alias": "Missing",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DropCopyRiskServer_recon",
     "select": [
      [
       {
        "params": [
         "DropCopyRiskServer_MissingOther"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}