{
 "title": "Capacity Utilisation",
 "tags": [ "cicd-managed" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES  WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "Metal Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temporary Metal Servers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU Utilization - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT 100 - mean(\"value\")\nFROM \"cpu_value\"\nWHERE (\"type_instance\"::tag = 'idle' AND \"host\"::tag =~ /^TA-[A-Z]{3}-[A-Z]-9[0-9]$/) AND $timeFilter\nGROUP BY time($__interval), \"host\"::tag fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance::tag", "operator": "=", "value": "idle" },
      { "condition": "AND", "key": "host::tag", "operator": "=", "value": "TA-TKY-A-99" }
     ]
    }
   ]
  },
  {
   "title": "Production Trading Servers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU Utilization - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT 100 - mean(\"value\")\nFROM \"cpu_value\"\nWHERE (\"type_instance\"::tag = 'idle' AND \"host\"::tag =~ /^TA-[A-Z]{3}-[A-Z]-[0-6][0-6]$/) AND $timeFilter\nGROUP BY time($__interval), \"host\"::tag fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance::tag", "operator": "=", "value": "idle" },
      { "condition": "AND", "key": "host::tag", "operator": "=", "value": "TA-TKY-A-99" }
     ]
    }
   ]
  },
  { "title": "InfluxDb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Crypto InfluxDB - CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU Utilization - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT 100 - mean(\"value\")\nFROM \"cpu_value\"\nWHERE (\"type_instance\"::tag = 'idle' AND \"host\"::tag =~ /^Crypto-InfluxDB-[0-9]{2}$/) AND $timeFilter\nGROUP BY time($__interval), \"host\"::tag fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance::tag", "operator": "=", "value": "idle" },
      { "condition": "AND", "key": "host::tag", "operator": "=", "value": "TA-TKY-A-99" }
     ]
    }
   ]
  },
  {
   "title": "Crypto InfluxDB - Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Memory Utilization - $tag_host - $tag_type_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT mean(\"value\")\nFROM \"memory_value\"\nWHERE (\"type_instance\" = 'used'\n    OR \"type_instance\" = 'free'\n    OR \"type_instance\" = 'buffered'\n    OR \"type_instance\" = 'cached'\n    OR \"type_instance\" = 'slab_recl'\n    OR \"type_instance\" = 'slab_unrecl')\nAND \"host\"::tag =~ /^Crypto-InfluxDB-[0-9]{2}$/\nAND $timeFilter\nGROUP BY time($interval), \"type_instance\"::tag, \"host\"::tag\nfill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance::tag", "operator": "=", "value": "idle" },
      { "condition": "AND", "key": "host::tag", "operator": "=", "value": "TA-TKY-A-99" }
     ]
    }
   ]
  },
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Grafana",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU Utilization - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT 100 - mean(\"value\")\nFROM \"cpu_value\"\nWHERE (\"type_instance\"::tag = 'idle' AND \"host\"::tag =~ /(?i)GRAFANA$/) AND $timeFilter\nGROUP BY time($__interval), \"host\"::tag fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance::tag", "operator": "=", "value": "idle" },
      { "condition": "AND", "key": "host::tag", "operator": "=", "value": "TA-TKY-A-99" }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Network -  PING Servers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU Utilization - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT 100 - mean(\"value\")\nFROM \"cpu_value\"\nWHERE (\"type_instance\"::tag = 'idle' AND \"host\"::tag =~ /(?i)^ping/) AND $timeFilter\nGROUP BY time($__interval), \"host\"::tag fill(previous)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance::tag", "operator": "=", "value": "idle" },
      { "condition": "AND", "key": "host::tag", "operator": "=", "value": "TA-TKY-A-99" }
     ]
    }
   ]
  },
  {
   "title": "All Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Servers",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "CPU Utilization - $tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu_value",
       "query": "SELECT 100 - mean(\"value\") AS \"busy\" FROM \"cpu_value\" WHERE \"type_instance\" = 'idle' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"host\"::tag fill(previous)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}