{
 "title": "Server - Disk Metrics",
 "description": "This dashboard provides various performance metrics for Linux systems, with templating to select the influxdb datasource and host.",
 "tags": [
  "linux",
  "disk_monitoring",
  "cicd-managed"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES  WITH KEY = \"host\""
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "SHOW TAG VALUES FROM \"df_value\" WITH KEY = \"instance\"\n"
   },
   { "name": "interval", "query": "10s,1m,5m,15m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "1.0 System Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "root (/) - Free & Used",
   "type": "stat",
   "gridPos": { "h": 22, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_instance Free",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND $timeFilter  AND \"instance\" = 'root'  GROUP BY time($interval) , \"instance\"   fill(null) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_instance Used ",
     "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'used' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND $timeFilter  AND \"instance\" = 'root'  GROUP BY time($interval) , \"instance\"   fill(null) "
    }
   ]
  },
  {
   "title": "/root - Free & Used - Monitoring",
   "type": "table",
   "gridPos": { "h": 22, "w": 8, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT *  FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^${host}$/ AND \"instance\" = 'root' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "1.1 System Disk - Rocky 9 - /boot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "/boot - Free & Used",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_instance Free",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND $timeFilter  AND \"instance\" = 'boot'  GROUP BY time($interval) , \"instance\"   fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_instance Used ",
       "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'used' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND $timeFilter  AND \"instance\" = 'boot'  GROUP BY time($interval) , \"instance\"   fill(null) "
      }
     ]
    },
    {
     "title": "/boot - Free & Used",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT *  FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^${host}$/ AND \"instance\" = 'boot' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "2.1 Non-Root Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "/local  - Free & Used",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_instance Free",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND $timeFilter  AND \"instance\" = 'local'  GROUP BY time($interval) , \"instance\"   fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_instance Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'used' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND $timeFilter  AND \"instance\" = 'local'  GROUP BY time($interval) , \"instance\"   fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "/local - Free & Used",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT *  FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^${host}$/ AND \"instance\" = 'local' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "2.2 Non Root Disk - InfluxDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "/local - Free",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_instance Free",
       "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND $timeFilter   GROUP BY time($interval) , \"instance\"   fill(null) "
      }
     ]
    },
    {
     "title": "/local-data* Host",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 34 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT *  FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^${host}$/  AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "/local-data* - Used",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_instance Used",
       "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'used' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND $timeFilter   GROUP BY time($interval) , \"instance\"   fill(null) "
      }
     ]
    }
   ]
  },
  {
   "title": "3. Non Root Disk - Zesty",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "/data  - Free & Used",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_instance Free",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND $timeFilter  AND \"instance\" = 'data'  GROUP BY time($interval) , \"instance\"   fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_instance Used",
       "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'used' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND $timeFilter  AND \"instance\" = 'data'  GROUP BY time($interval) , \"instance\"   fill(null) "
      }
     ]
    },
    {
     "title": "/data - Free & Used",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT *  FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^${host}$/ AND \"instance\" = 'data' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Non Root Disk - To be terminated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "/rearch_backup - Free & Used",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_instance Free",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND $timeFilter  AND \"instance\" = 'research_backup'  GROUP BY time($interval) , \"instance\"   fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_instance Used",
       "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'used' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND $timeFilter  AND \"instance\" = 'research_backup'  GROUP BY time($interval) , \"instance\"   fill(null) "
      }
     ]
    },
    {
     "title": "/research_backup - Free & Used",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT *  FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^${host}$/ AND \"instance\" = 'research_backup' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "/local/ebs_store  - Free & Used",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_instance Free",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND $timeFilter  AND \"instance\" = 'local-ebs_store'  GROUP BY time($interval) , \"instance\"   fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_instance Used",
       "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'used' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND $timeFilter  AND \"instance\" = 'local-ebs_store'  GROUP BY time($interval) , \"instance\"   fill(null) "
      }
     ]
    },
    {
     "title": "/local/ebs_store  - Free & Used",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT *  FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^${host}$/ AND \"instance\" = 'local-ebs_store' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "All Disk Size from InfluxDb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk - Free & Used",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "$tag_instance Free",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'free' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/   AND \"instance\" =~ /^$instance$/   AND $timeFilter GROUP BY time($interval) , \"instance\"   fill(null) ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_instance Used",
       "query": "SELECT sum(value) FROM \"df_value\" WHERE \"type_instance\" = 'used' AND \"type\" = 'df_complex' AND \"host\" =~ /^$host$/ AND \"instance\" =~ /^$instance$/  AND $timeFilter GROUP BY time($interval), \"instance\"  fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk utilization %",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage Percentage",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_instance Used Space (%)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(value) FROM \"df_value\" WHERE \"type_instance\" = 'used' AND \"type\" = 'percent_bytes' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"instance\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_instance Used Inode (%)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(value) FROM \"df_value\" WHERE \"type_instance\" = 'used' AND \"type\" = 'percent_inodes' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"instance\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_instance I/O Time",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(mean(value), 1s) FROM \"disk_io_time\" WHERE \"type\" = 'disk_io_time' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"instance\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Weighted I/O Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_instance I/O Time",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(mean(value), 1s) FROM \"disk_weighted_io_time\" WHERE \"type\" = 'disk_io_time' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"instance\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$tag_instance Data Read",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(mean(value), 1s) FROM \"disk_read\" WHERE \"type\" = 'disk_octets' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"instance\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_instance Data Write",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(mean(value), 1s) FROM \"disk_write\" WHERE \"type\" = 'disk_octets' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"instance\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk I/O Pending Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_instance queue length",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(mean(value), 1s) FROM \"disk_value\" WHERE \"type\" = 'pending_operations' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"instance\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}