{
 "title": "Crypto-Account-Level-Tracking DeltaSum",
 "tags": [ "cicd-managed" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "level",
    "label": "Mimid Account Level",
    "query": "SHOW TAG VALUES WITH KEY IN (\"level\")"
   },
   {
    "name": "label",
    "label": "Mimid Label",
    "query": "SHOW TAG VALUES WITH KEY = \"label\" WHERE \"level\" =~ /^$level$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Daily PnL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT (last(\"sum_last_pnl\")) as PNL\nFROM (\n    SELECT SUM(last_pnl) AS sum_last_pnl FROM (\n        SELECT last(\"pnl\") AS last_pnl \n        FROM \"default\".\"acct_lvl_daily_pnl\"\n        WHERE (\"level\" =~ /^1$/) AND \"label\" !~ /^SLN--DEFI$/ \n        AND $timeFilter\n        GROUP BY time($__interval), \"label\", \"level\"\n    ) \n    GROUP BY time($__interval)\n)\n"
    }
   ]
  },
  {
   "title": "Daily Trade Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStatsTestNew\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acct_lvl_daily_trade_vol\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"trade_vol\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"0\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Risk (Notional)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStatsTestNew\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acct_lvl_grp_risk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grp_risk\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"0\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Daily PnL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_daily_pnl",
     "query": "SELECT SUM(last_pnl) FROM (\n    SELECT last(\"pnl\") AS last_pnl \n    FROM \"default\".\"acct_lvl_daily_pnl\"\n    WHERE (\"level\" =~ /^1$/) AND \"label\" !~ /^SLN--DEFI$/  AND \"label\" !~ /^SLN--DEFI$/  AND \"label\" !~ /^SLN--BLUEFIN$/ \n    AND $timeFilter\n    GROUP BY time($__interval), \"label\", \"level\"\n) \nGROUP BY time($__interval)\n",
     "select": [
      [
       { "params": [ "pnl" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "label::tag", "operator": "!=", "value": "SLN--DEFI" },
      { "condition": "AND", "key": "level::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Daily Trade Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStatsTestNew\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acct_lvl_daily_trade_vol\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"trade_vol\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"0\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)  \r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Risk (Notional)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStatsTestNew\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acct_lvl_grp_risk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grp_risk\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"0\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)  \r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Daily PnL by Mimid Account Level ${level}",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_daily_pnl",
     "query": "SELECT last(\"pnl\") FROM \"default\".\"acct_lvl_daily_pnl\" WHERE (\"level\" =~ /^$level$/ AND \"label\" =~ /^$label$/ AND \"pnl\" != 0) AND $timeFilter GROUP BY time($__interval), \"label\", \"level\" fill(none) ",
     "select": [
      [
       { "params": [ "pnl" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=~", "value": "/^$level$/" },
      { "condition": "AND", "key": "label", "operator": "=~", "value": "/^$label$/" },
      { "condition": "AND", "key": "pnl", "operator": "!=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Daily PnL by Mimid Account Level ${level}",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_daily_pnl",
     "query": "from(bucket: \"Mimid_PnLStatsTestNew\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acct_lvl_daily_pnl\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pnl\")\r\n  |> filter(fn: (r) => r[\"level\"] =~ /^(${level:pipe})$/)\r\n  |> filter(fn: (r) => r[\"label\"] =~ /^(${label:pipe})$/)\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> difference()\r\n  |> cumulativeSum()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "pnl" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=~", "value": "/^$label$/" },
      { "condition": "AND", "key": "level", "operator": "=~", "value": "/^$level$/" },
      { "condition": "AND", "key": "label::tag", "operator": "!=", "value": "SLN--BLUEFIN" }
     ]
    }
   ]
  },
  {
   "title": "Daily Trade Volume by Mimid Account Level ${level}",
   "type": "stat",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_daily_trade_vol",
     "query": "SELECT last(\"trade_vol\") FROM \"default\".\"acct_lvl_daily_trade_vol\" WHERE (\"level\" =~ /^$level$/ AND \"label\" =~ /^$label$/ AND abs(\"trade_vol\") > 0) AND $timeFilter GROUP BY time($__interval), \"label\", \"level\" fill(none)",
     "select": [
      [
       { "params": [ "trade_vol" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=~", "value": "/^$level$/" },
      { "condition": "AND", "key": "label", "operator": "=~", "value": "/^$label$/" },
      { "condition": "AND", "key": "trade_vol::field", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Daily Trade Volume by Mimid Account Level ${level}",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 18, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_daily_trade_vol",
     "query": "from(bucket: \"Mimid_PnLStatsTestNew\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acct_lvl_daily_trade_vol\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"trade_vol\")\r\n  |> filter(fn: (r) => r[\"level\"] =~ /^(${level:pipe})$/)\r\n  |> filter(fn: (r) => r[\"label\"] =~ /^(${label:pipe})$/)\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)  \r\n  |> difference()\r\n  |> cumulativeSum()\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "trade_vol" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=~", "value": "/^$label$/" },
      { "condition": "AND", "key": "level", "operator": "=~", "value": "/^$level$/" }
     ]
    }
   ]
  },
  {
   "title": "Risk (Notional) by Mimid Account Level ${level}",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_grp_risk",
     "query": "from(bucket: \"Mimid_PnLStatsTestNew\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acct_lvl_grp_risk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grp_risk\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"${level}\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "grp_risk" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=~", "value": "/^$level$/" },
      { "condition": "AND", "key": "label", "operator": "=~", "value": "/^$label$/" }
     ]
    }
   ]
  },
  {
   "title": "Risk (Notional) by Mimid Account Level ${level}",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_grp_risk",
     "query": "from(bucket: \"Mimid_PnLStatsTestNew\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acct_lvl_grp_risk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grp_risk\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"${level}\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)  \r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "grp_risk" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=~", "value": "/^$label$/" },
      { "condition": "AND", "key": "level", "operator": "=~", "value": "/^$level$/" }
     ]
    }
   ]
  },
  {
   "title": "PPM by Mimid Account Level ${level}",
   "type": "stat",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_daily_pnl_trade_vol_ratio",
     "query": "from(bucket: \"Mimid_PnLStatsTestNew\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acct_lvl_grp_risk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grp_risk\")\r\n  |> filter(fn: (r) => contains(value: r[\"level\"], set: ${level:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"label\"], set: ${label:json}))\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "pnl_trade_vol_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=~", "value": "/^$level$/" },
      { "condition": "AND", "key": "label", "operator": "=~", "value": "/^$label$/" }
     ]
    }
   ]
  },
  {
   "title": "PPM by Mimid Account Level ${level}",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 18, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "($A > 1000) * (1000 - $A) + $A + ($A < -1000) * (-1000 - $A)",
     "type": "math"
    }
   ]
  }
 ]
}