{
 "title": "Drop Copy ICO",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_id",
    "query": "SELECT DISTINCT account_id FROM dropcopy_assets WHERE date = CURDATE();"
   },
   {
    "name": "trade_filter_assets",
    "query": "SELECT DISTINCT symbol FROM dropcopy_trades WHERE $__timeFilter(datetime) AND account_id IN (${account_id:sqlstring}) ;"
   }
  ]
 },
 "panels": [
  {
   "title": "Recent Trade for selected account",
   "type": "table",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "sln_dropcopy",
     "rawSql": "SELECT usd_notional, datetime, selini_symbol, symbol, quantity, side, price\nFROM sln_dropcopy.dropcopy_trades\nWHERE account_id IN (${account_id:sqlstring}) AND symbol IN (${trade_filter_assets:sqlstring})\nORDER BY datetime DESC\nLIMIT 50\n"
    }
   ]
  },
  {
   "title": "Minutes Since Last update",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    account_id, \n    account_name, \n    exchange_name, \n    TIMESTAMPDIFF(\n        MINUTE, \n        FROM_UNIXTIME(MAX(timestamp) / 1000), \n        NOW()\n    ) AS \"minutes_since_last_update\"\nFROM sln_dropcopy.dropcopy_accounts\nWHERE account_id IN (${account_id:sqlstring})\nGROUP BY account_id, account_name, exchange_name\nORDER BY account_id;\n"
    }
   ]
  },
  {
   "title": "Lowest exchange margin ratio",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n    dca.account_id,\n    dca.bucket,\n    dca.exchange_name,\n    dca.status,\n    dca.net_value,\n    dca.maintenance_margin,\n    dca.exchange_margin_ratio,\n    dca.timestamp\nFROM \n    sln_dropcopy.dropcopy_accounts dca\nINNER JOIN (\n    SELECT \n        account_id, \n        bucket, \n        MAX(timestamp) AS max_timestamp\n    FROM \n        sln_dropcopy.dropcopy_accounts\n    WHERE \n        exchange_name = 'BINANCE' AND\n        exchange_margin_ratio IS NOT NULL\n    GROUP BY \n        account_id, bucket\n) AS recent\nON \n    dca.account_id = recent.account_id AND \n    dca.bucket = recent.bucket AND \n    dca.timestamp = recent.max_timestamp\nWHERE \n    dca.exchange_name = 'BINANCE' AND \n    dca.exchange_margin_ratio IS NOT NULL\nORDER BY \n    dca.exchange_margin_ratio ASC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "title": "Assets table for selected account",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \n    dca.timestamp AS \"time\",\n    dca.account_id,\n    dca.bucket,\n    dca.asset,\n    dca.status,\n    dca.total,\n    dca.available_for_trading,\n    dca.free,\n    dca.locked,\n    dca.borrowed,\n    dca.interest,\n    dca.total_usd,\n    dca.available_for_trading_usd,\n    dca.unrealized_profit,\n    dca.maintenance_margin\nFROM \n    sln_dropcopy.dropcopy_assets dca\nINNER JOIN (\n    SELECT \n        asset, \n        account_id, \n        bucket, \n        MAX(timestamp) AS max_timestamp\n    FROM \n        sln_dropcopy.dropcopy_assets\n    WHERE \n        account_id IN (${account_id:sqlstring}) AND $__timeFilter(datetime)\n    GROUP BY \n        asset, account_id, bucket\n) AS recent ON dca.asset = recent.asset \n    AND dca.account_id = recent.account_id \n    AND dca.bucket = recent.bucket \n    AND dca.timestamp = recent.max_timestamp\nLIMIT 50000;\n"
    }
   ]
  },
  {
   "title": "net_usd_value of selected account",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT net_value AS \"net_value_usd\", timestamp AS \"time\", account_id, account_name, exchange_name, currency\nFROM sln_dropcopy.dropcopy_accounts\nWHERE account_id IN (${account_id:sqlstring})\nLIMIT 50000"
    }
   ]
  },
  {
   "title": "Position (quantity_notional)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT quantity_notional AS \"value\", timestamp AS \"time\", selini_symbol, account_id\nFROM sln_dropcopy.dropcopy_positions \nWHERE account_id IN (${account_id:sqlstring})\nLIMIT 50000"
    }
   ]
  },
  {
   "title": "asset_balance (total_usd)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT total_usd AS \"total_usd\", timestamp AS \"time\", asset, account_id, bucket\nFROM sln_dropcopy.dropcopy_assets \nWHERE account_id IN (${account_id:sqlstring})\nLIMIT 50000"
    }
   ]
  }
 ]
}