{
 "title": "drop_copy",
 "tags": [ "cicd-managed" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "account_id",
    "query": "SELECT DISTINCT account_id FROM dropcopy_assets_v2 WHERE date = CURDATE();"
   },
   {
    "name": "trade_filter_assets",
    "query": "SELECT DISTINCT symbol FROM dropcopy_trades_v2 WHERE account_id IN (${account_id:sqlstring}) AND $__timeFilter(datetime);"
   }
  ]
 },
 "panels": [
  {
   "title": "Recent Trade for selected account",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "sln_dropcopy",
     "rawSql": "SELECT usd_notional, datetime, selini_symbol, symbol, quantity, side, price\nFROM sln_dropcopy.dropcopy_trades_v2\nWHERE $__timeFilter(datetime) AND account_id IN (${account_id:sqlstring}) AND symbol IN (${trade_filter_assets:sqlstring}) \nORDER BY datetime DESC\nLIMIT 50\n"
    }
   ]
  },
  {
   "title": "Minutes Since Last update",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    account_id, \n    account_name, \n    exchange_name, \n    datetime,\n    TIMESTAMPDIFF(\n        MINUTE, \n        FROM_UNIXTIME(MAX(timestamp) / 1000), \n        NOW()\n    ) AS \"minutes_since_last_update\"\nFROM sln_dropcopy.dropcopy_accounts_v2\nWHERE account_id IN (${account_id:sqlstring})    AND $__timeFilter(datetime)\nGROUP BY account_id, account_name, exchange_name\nORDER BY account_id;\n"
    }
   ]
  },
  {
   "title": "Lowest exchange margin ratio",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n    dca.account_id,\n    dca.bucket,\n    dca.exchange_name,\n    dca.status,\n    dca.net_value,\n    dca.maintenance_margin,\n    dca.exchange_margin_ratio,\n    dca.timestamp\nFROM \n    sln_dropcopy.dropcopy_accounts_v2 dca\nINNER JOIN (\n    SELECT \n        account_id, \n        bucket, \n        MAX(timestamp) AS max_timestamp\n    FROM \n        sln_dropcopy.dropcopy_accounts_v2\n    WHERE \n        exchange_name = 'BINANCE' AND\n        exchange_margin_ratio IS NOT NULL\n        AND $__timeFilter(datetime)\n    GROUP BY \n        account_id, bucket\n) AS recent\nON \n    dca.account_id = recent.account_id AND \n    dca.bucket = recent.bucket AND \n    dca.timestamp = recent.max_timestamp\nWHERE \n    dca.exchange_name = 'BINANCE' AND \n    dca.exchange_margin_ratio IS NOT NULL\n    AND $__timeFilter(datetime)\nORDER BY \n    dca.exchange_margin_ratio ASC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "title": "Assets table for selected account",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \n    dca.timestamp AS \"time\",\n    dca.account_id,\n    dca.bucket,\n    dca.asset,\n    dca.status,\n    dca.total,\n    dca.available_for_trading,\n    dca.free,\n    dca.locked,\n    dca.borrowed,\n    dca.interest,\n    dca.total_usd,\n    dca.available_for_trading_usd,\n    dca.unrealized_profit,\n    dca.maintenance_margin\nFROM \n    sln_dropcopy.dropcopy_assets_v2 as dca\nINNER JOIN (\n    SELECT \n        asset, \n        account_id, \n        bucket, \n        MAX(timestamp) AS max_timestamp\n    FROM \n        sln_dropcopy.dropcopy_assets_v2\n    WHERE \n        account_id IN (${account_id:sqlstring}) AND $__timeFilter(datetime)\n    GROUP BY \n        asset, account_id, bucket\n) AS recent ON dca.asset = recent.asset \n    AND dca.account_id = recent.account_id \n    AND dca.bucket = recent.bucket \n    AND dca.timestamp = recent.max_timestamp\nLIMIT 5000;\n"
    }
   ]
  },
  {
   "title": "net_usd_value of selected account",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT \n    net_value AS \"net_value_usd\", \n    datetime AS \"time\",\n    `date`,\n    account_id, \n    account_name, \n    exchange_name, \n    currency\nFROM \n    sln_dropcopy.dropcopy_accounts_v2\nWHERE \n    account_id IN (${account_id:sqlstring})\n    AND `date` >= DATE(FROM_UNIXTIME(${__from}/1000))\n    AND `date` <= DATE(FROM_UNIXTIME(${__to}/1000))\n    AND $__timeFilter(datetime)\nLIMIT 5000\n"
    }
   ]
  },
  {
   "title": "Position (quantity_notional)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT \n    quantity_notional AS \"value\", \n    datetime AS \"time\", \n    `date`,\n    selini_symbol, \n    account_id\nFROM \n    sln_dropcopy.dropcopy_positions_v2\nWHERE \n    account_id IN (${account_id:sqlstring})\n    AND `date` >= DATE(FROM_UNIXTIME(${__from}/1000))\n    AND `date` <= DATE(FROM_UNIXTIME(${__to}/1000))\n    AND $__timeFilter(datetime)\nLIMIT 5000\n\n\n\n"
    }
   ]
  },
  {
   "title": "asset_balance (total_usd)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT \n    total_usd AS \"total_usd\", \n    datetime AS \"time\", \n    `date`,\n    asset, \n    account_id, \n    bucket\nFROM \n    sln_dropcopy.dropcopy_assets_v2\nWHERE \n    account_id IN (${account_id:sqlstring})\n    AND `date` >= DATE(FROM_UNIXTIME(${__from}/1000))\n    AND `date` <= DATE(FROM_UNIXTIME(${__to}/1000))\n    AND $__timeFilter(datetime)\nLIMIT 5000\n"
    }
   ]
  }
 ]
}