{
 "title": "FH Metrics - fh-stats.selini.tech",
 "tags": [
  "New InfluxDb for Field Handlers",
  "cicd-managed"
 ],
 "time": { "from": "2024-10-08T20:09:54.941Z", "to": "2024-10-08T20:11:27.513Z" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "SHOW TAG VALUES ON \"omnia_stats\" FROM \"fh_exch_to_recv_ns\" WITH KEY=\"hostname\""
   },
   {
    "name": "app_name",
    "label": "FH Name",
    "query": "SHOW TAG VALUES ON \"omnia_stats\" FROM \"fh_json_sz\" WITH KEY=\"app_name\""
   },
   {
    "name": "symbol",
    "label": "Symbol",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"fh_json_full_cycle_ns\" WITH KEY=\"instrument\" WHERE \"app_name\" = $app_name"
   },
   {
    "name": "msg_type",
    "label": "Message",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"fh_json_full_cycle_ns\" WITH KEY=\"msg_type\" WHERE \"app_name\" = $app_name"
   }
  ]
 },
 "panels": [
  {
   "title": "JSON Full Cycle Latency - Msg Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fh_json_full_cycle_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Tail delete book stats",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "deque_sz $tag_hostname $tag_app_name $tag_instrument",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_delete_book_deleted_levels_deque_sz",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_book_update_delta_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "map_sz $tag_hostname $tag_app_name $tag_instrument",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail_delete_book_deleted_levels_sz",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_book_update_delta_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "book_sz $tag_hostname $tag_app_name $tag_instrument",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "l2book_num_lvls",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_book_update_delta_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "JSON Full Cycle Exclude Book Update (i.e. FH receive -> FH publish delta)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fh_json_full_cycle_exclude_book_update_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "FH lws Process Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "lws_process_ns",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_book_update_delta_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "JSON Full Cycle Count - Msg Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fh_json_full_cycle_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Exchange to FH Receive",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fh_exch_to_recv_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_recv_to_publish_ns\" WHERE (\"app_name\"::tag = 'bullish_fh_0_TA-SGP-C-14' AND \"instrument\"::tag = 'BTC/USDT' AND \"msg_type\"::tag = 'BBO_UPDATE') AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Exchange Internal Latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fh_exch_internal_latency_ms",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_recv_to_publish_ns\" WHERE (\"app_name\"::tag = 'bullish_fh_0_TA-SGP-C-14' AND \"instrument\"::tag = 'BTC/USDT' AND \"msg_type\"::tag = 'BBO_UPDATE') AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "FH Timer Latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "timer_latency",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_book_update_delta_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "FH Recv to Packet Send Latency - Feed Handler Delay",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fh_recv_to_publish_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_recv_to_publish_ns\" WHERE (\"app_name\"::tag = 'bullish_fh_0_TA-SGP-C-14' AND \"instrument\"::tag = 'BTC/USDT' AND \"msg_type\"::tag = 'BBO_UPDATE') AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "FH Book Update Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fh_book_update_delta_ns",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_book_update_delta_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "L2book On Update Time - Time taken by on_update function",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_instrument",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "l2book_on_update_ns",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_book_update_delta_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "L2book Publish Full Snapshot Time - Time taken by publish_full_snapshot function",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_instrument",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "l2book_pub_full_snap_ns",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_book_update_delta_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "L2book Num Lvls",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_instrument",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "l2book_num_lvls",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_book_update_delta_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WS Open connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_instrument",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "total_connected",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_book_update_delta_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Num Symbols All WS sessions disconnected",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_instrument",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "max::field" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "num_all_disconnects",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_book_update_delta_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "L2book Update Num Lvls",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_instrument",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "l2book_update_num_lvls",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_book_update_delta_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "FH Last Recv to Recv - Time between Json msgs",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_hostname $col $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fh_cycle_dist_ns",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_cycle_dist_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/) AND $timeFilter GROUP BY \"app_name\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "JSON Size",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 228 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fh_json_sz",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_json_sz\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet Size - Size of internal Binary Msg put on FH ring channel",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 242 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fh_packet_sz",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_packet_sz\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet Size - Count of internal Binary Msg put on FH ring channel",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 256 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_hostname $tag_app_name $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "fh_packet_sz",
     "query": "SELECT \"max\" FROM \"autogen\".\"fh_packet_sz\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/) AND $timeFilter GROUP BY \"app_name\"::tag, \"msg_type\"::tag, \"instrument\"::tag",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  }
 ]
}