{
 "title": "Global Latency Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "msg_type",
    "label": "Message",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"fh_json_sz\" WITH KEY=\"msg_type\""
   },
   {
    "name": "symbol",
    "label": "Symbol",
    "query": "SELECT DISTINCT SUBSTRING_INDEX(symbol, '@', 1) AS prefix\nFROM md_subscriptions ORDER BY prefix"
   },
   {
    "name": "exchange",
    "label": "Exchange",
    "query": "SELECT DISTINCT SUBSTRING(symbol, LOCATE('@', symbol) + 1) AS suffix FROM md_subscriptions ORDER BY suffix"
   },
   {
    "name": "apub",
    "label": "Source Host",
    "query": "SELECT DISTINCT A_publisher \nFROM md_subscriptions \nWHERE SUBSTRING_INDEX(symbol, '@', 1) IN (${symbol:sqlstring})\n  AND SUBSTRING(symbol, LOCATE('@', symbol) + 1) IN (${exchange:sqlstring})\nORDER BY A_publisher"
   },
   {
    "name": "afh",
    "label": "Source FH",
    "query": "SELECT DISTINCT A_fh \nFROM md_subscriptions \nWHERE SUBSTRING_INDEX(symbol, '@', 1) IN (${symbol:sqlstring})\n  AND SUBSTRING(symbol, LOCATE('@', symbol) + 1) IN (${exchange:sqlstring}) AND A_publisher IN (${apub:sqlstring}) \nORDER BY A_fh"
   },
   {
    "name": "brep",
    "label": "B-feed Hop",
    "query": "SELECT DISTINCT B_repeater\nFROM md_subscriptions \nWHERE SUBSTRING_INDEX(symbol, '@', 1) IN (${symbol:sqlstring})\n  AND SUBSTRING_INDEX(symbol, '@', -1) IN (${exchange:sqlstring})\n  AND A_publisher IN (${apub:sqlstring})\n  AND A_fh IN (${afh:sqlstring})\n  AND B_repeater != ''\nORDER BY B_repeater"
   },
   {
    "name": "crep",
    "label": "C-Feed Hop",
    "query": "SELECT DISTINCT C_repeater\nFROM md_subscriptions \nWHERE SUBSTRING_INDEX(symbol, '@', 1) IN (${symbol:sqlstring})\n  AND SUBSTRING_INDEX(symbol, '@', -1) IN (${exchange:sqlstring})\n  AND A_publisher IN (${apub:sqlstring})\n  AND A_fh IN (${afh:sqlstring})\n  AND C_repeater != ''\nORDER BY C_repeater"
   },
   {
    "name": "machine_A",
    "label": "Destination A",
    "query": "SELECT DISTINCT UPPER(machine) AS machine\nFROM md_subscriptions \nWHERE SUBSTRING_INDEX(symbol, '@', 1) IN (${symbol:sqlstring})\n  AND SUBSTRING_INDEX(symbol, '@', -1) IN (${exchange:sqlstring})\n  AND (A_publisher IN (${apub:sqlstring}) OR A_fh IN (${afh:sqlstring}))\nORDER BY UPPER(machine)"
   },
   {
    "name": "machine_B",
    "label": "Destination B",
    "query": "SELECT DISTINCT UPPER(machine)\nFROM md_subscriptions \nWHERE SUBSTRING_INDEX(symbol, '@', 1) IN (${symbol:sqlstring})\n  AND SUBSTRING(symbol, LOCATE('@', symbol) + 1) IN (${exchange:sqlstring}) AND ( A_fh IN (${afh:sqlstring}) AND B_repeater in (${brep:sqlstring}) AND B_publisher != 'Not found' AND B_publisher != '')\nORDER BY machine"
   },
   {
    "name": "machine_C",
    "label": "Destination C",
    "query": "SELECT DISTINCT UPPER(machine)\nFROM md_subscriptions \nWHERE SUBSTRING_INDEX(symbol, '@', 1) IN (${symbol:sqlstring})\n  AND SUBSTRING(symbol, LOCATE('@', symbol) + 1) IN (${exchange:sqlstring}) AND ( A_fh IN (${afh:sqlstring}) AND C_repeater in (${crep:sqlstring})  AND C_publisher != 'Not found' AND C_publisher != '')\nORDER BY machine"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Components",
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center> <img src=/public/img/network_components.png> </center>"
   },
   "targets": [
    {
     "alias": "$tag_app_name $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fh_exch_internal_latency_ms",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_recv_to_publish_ns\" WHERE (\"app_name\"::tag = 'bullish_fh_0_TA-SGP-C-14' AND \"instrument\"::tag = 'BTC/USDT' AND \"msg_type\"::tag = 'BBO_UPDATE') AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$afh$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" }
     ]
    }
   ]
  },
  {
   "title": "Exch Txn to Exch Publish (t1 - t0)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fh_exch_internal_latency_ms",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_recv_to_publish_ns\" WHERE (\"app_name\"::tag = 'bullish_fh_0_TA-SGP-C-14' AND \"instrument\"::tag = 'BTC/USDT' AND \"msg_type\"::tag = 'BBO_UPDATE') AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$afh$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" }
     ]
    }
   ]
  },
  {
   "title": "Exch to FH Recv (t2-t1)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fh_exch_to_recv_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_recv_to_publish_ns\" WHERE (\"app_name\"::tag = 'bullish_fh_0_TA-SGP-C-14' AND \"instrument\"::tag = 'BTC/USDT' AND \"msg_type\"::tag = 'BBO_UPDATE') AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "app_name::tag", "operator": "=~", "value": "/^$afh$/" }
     ]
    }
   ]
  },
  {
   "title": "FH Recv to FH Pub (t3-t2)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fh_recv_to_publish_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_recv_to_publish_ns\" WHERE (\"app_name\"::tag = 'bullish_fh_0_TA-SGP-C-14' AND \"instrument\"::tag = 'BTC/USDT' AND \"msg_type\"::tag = 'BBO_UPDATE') AND $timeFilter GROUP BY time(1s) fill(none)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$afh$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" }
     ]
    }
   ]
  },
  {
   "title": "FH/Repeater Pub to Pub Recv (t4-t3, t8-t7)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_src_to_pub_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$apub$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_src_to_pub_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$brep$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_src_to_pub_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$crep$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" }
     ]
    }
   ]
  },
  {
   "title": "Pub Recv to Pub Pub (t5-t4, t9-t8)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument msg=$tag_msg_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_read_rc_to_post_write_socket_delay_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$apub$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" }
     ]
    },
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument msg=$tag_msg_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_read_rc_to_post_write_socket_delay_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$brep$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" }
     ]
    },
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument msg=$tag_msg_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_read_rc_to_post_write_socket_delay_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$crep$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" }
     ]
    }
   ]
  },
  {
   "title": "Tao Recv to Tao Done",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_host max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NetworkDispatchCycles",
     "query": "SELECT max(\"average\") FROM \"autogen\".\"MDBookUpdateLatency\" WHERE (\"host\"::tag = 'TA-TKY-A-13')",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$machine_A$/" }
     ]
    },
    {
     "alias": "$tag_host max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NetworkDispatchCycles",
     "query": "SELECT max(\"average\") FROM \"autogen\".\"MDBookUpdateLatency\" WHERE (\"host\"::tag = 'TA-TKY-A-13')",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$machine_B$/" }
     ]
    },
    {
     "alias": "$tag_host max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NetworkDispatchCycles",
     "query": "SELECT max(\"max\")  / 3 FROM \"default_mimid_retention\".\"NetworkDispatchCycles\" WHERE (\"host\"::tag =~ /^$machine_C$/) AND $timeFilter GROUP BY time($__interval), \"host\"::tag fill(none)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$machine_C$/" }
     ]
    }
   ]
  },
  {
   "title": "Pub Pub to Repeater Recv (t6-t5)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "b_rep $tag_source $tag_exchange $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" }
     ],
     "measurement": "publish_delay_ns",
     "query": "SELECT \"max\" FROM \"autogen\".\"publish_delay_ns\" WHERE (\"hostname\"::tag =~ /^$b_rep$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"exchange\"::tag =~ /^$exchange$/) AND $timeFilter GROUP BY \"source\"::tag, \"msg_type\"::tag, \"instrument\"::tag, \"exchange\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$brep$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" }
     ]
    },
    {
     "alias": "c_rep $tag_source $tag_exchange $tag_instrument $tag_msg_type",
     "groupBy": [
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" }
     ],
     "measurement": "publish_delay_ns",
     "query": "SELECT \"max\" FROM \"autogen\".\"publish_delay_ns\" WHERE (\"hostname\"::tag =~ /^$c_rep$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"exchange\"::tag =~ /^$exchange$/) AND $timeFilter GROUP BY \"source\"::tag, \"msg_type\"::tag, \"instrument\"::tag, \"exchange\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$crep$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" }
     ]
    }
   ]
  },
  {
   "title": "Repeater Recv to Repeater Pub (t7-t6)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "b_rep $tag_source $tag_exchange $tag_instrument  $tag_msg_type",
     "groupBy": [
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" }
     ],
     "measurement": "process_delay_ns",
     "query": "SELECT \"max\" FROM \"autogen\".\"process_delay_ns\" WHERE (\"hostname\"::tag =~ /^$host$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"exchange\"::tag =~ /^$exchange$/) AND $timeFilter GROUP BY \"source\"::tag, \"msg_type\"::tag, \"instrument\"::tag, \"exchange\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$brep$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" }
     ]
    },
    {
     "alias": "c_rep $tag_source $tag_exchange $tag_instrument  $tag_msg_type",
     "groupBy": [
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" }
     ],
     "measurement": "process_delay_ns",
     "query": "SELECT \"max\" FROM \"autogen\".\"process_delay_ns\" WHERE (\"hostname\"::tag =~ /^$host$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"exchange\"::tag =~ /^$exchange$/) AND $timeFilter GROUP BY \"source\"::tag, \"msg_type\"::tag, \"instrument\"::tag, \"exchange\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$crep$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" }
     ]
    }
   ]
  }
 ]
}