{
 "title": "Publisher Metrics - pb-stats.selini.tech",
 "tags": [
  "New Dashboard for Publishers",
  "cicd-managed"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Publisher Host",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"ring_chan_queue_size\" WITH KEY=\"hostname\""
   },
   {
    "name": "exchange",
    "label": "Source Exchange",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"udp_pub_subscriber_count\" WITH KEY=\"exchange\" WHERE \"hostname\" =~ /^$host$/"
   },
   {
    "name": "instrument",
    "label": "Instrument",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"udp_pub_subscriber_count\" WITH KEY=\"instrument\" WHERE \"hostname\" =~ /^$host$/"
   },
   {
    "name": "message",
    "label": "Message",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"udp_pub_subscriber_count\" WITH KEY=\"msg_type\" WHERE \"hostname\" =~ /^$host$/"
   },
   {
    "name": "core",
    "label": "Core",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"udp_pub_subscriber_count\" WITH KEY=\"thread_id\" WHERE \"hostname\" =~ /^$host$/"
   },
   {
    "name": "app_name",
    "label": "App Name",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"udp_pub_subscriber_count\" WITH KEY=\"app_name\" WHERE \"hostname\" =~ /^$host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Read Src Ring Chan to Write Socket Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument msg=$tag_msg_type core=$tag_thread_id",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "thread_id::tag" ], "type": "tag" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_read_rc_to_post_write_socket_delay_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$instrument$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$message$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "thread_id::tag", "operator": "=~", "value": "/^$core$/" },
      { "condition": "AND", "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Source and Internal Ring Chan Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ring_chan::tag" ], "type": "tag" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" }
     ],
     "measurement": "ring_chan_queue_size",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Internal Ring Chan Queue Delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument msg=$tag_msg_type core=$tag_thread_id",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "thread_id::tag" ], "type": "tag" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_pub_rc_queue_delay_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$instrument$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$message$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "thread_id::tag", "operator": "=~", "value": "/^$core$/" },
      { "condition": "AND", "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Subscriptions (exch x instr)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$app_name",
     "groupBy": [
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_subscriber_count",
     "query": "SELECT sum(\"TOTAL\") from (SELECT last(\"max\") as \"TOTAL\" FROM \"autogen\".\"udp_pub_subscriber_count\" WHERE (\"hostname\"::tag =~/^$host$/ AND \"app_name\"::tag =~/^$app_name$/) AND $timeFilter GROUP BY time(10s), \"thread_id\"::tag, \"app_name\"::tag, \"exchange\"::tag, \"instrument\"::tag, \"hostname\"::tag) GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Source to Publisher Recv Delay ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_src_to_pub_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$instrument$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$message$/" },
      { "condition": "AND", "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread Ring Chan Read to Pre-Socket Write Delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument msg=$tag_msg_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_pub_rc_read_to_write_socket_delay_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$instrument$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$message$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Socket Write Delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument msg=$tag_msg_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_write_socket_delay_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$instrument$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$message$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "DPDK Prepare Send Delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument msg=$tag_msg_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_prepare_send_time_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$instrument$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$message$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Socket Cleanup Delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument msg=$tag_msg_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_cleanup_delay_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$instrument$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$message$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Subscriber Count in Thread",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument core=$tag_thread_id",
     "groupBy": [
      { "params": [ "thread_id::tag" ], "type": "tag" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_subscriber_count",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$instrument$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$message$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "thread_id::tag", "operator": "=~", "value": "/^$core$/" },
      { "condition": "AND", "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "DPDK Send Delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument msg=$tag_msg_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_dpdk_send_time_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$instrument$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$message$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Num Trade Packets Coalesced",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument msg=$tag_msg_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_num_packets_coalesce",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$instrument$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$message$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" }
     ]
    }
   ]
  },
  {
   "title": "First to Last Trade Coalesce Ns",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument msg=$tag_msg_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_trade_coalesce_ns",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$instrument$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$message$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" }
     ]
    }
   ]
  },
  {
   "title": "(Projected for subscribe count) Trade Coalescing Latency Savings Ns",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument msg=$tag_msg_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_subscriber_count",
     "query": "SELECT max(\"avg\") FROM \"autogen\".\"udp_pub_trade_coalesce_ns\" WHERE (\"instrument\"::tag =~ /^$instrument$/ AND \"hostname\"::tag =~ /^$host$/ AND \"msg_type\"::tag =~ /^$message$/ AND \"exchange\"::tag =~ /^$exchange$/) AND $timeFilter GROUP BY time($interval), \"app_name\"::tag, \"exchange\"::tag, \"instrument\"::tag, \"hostname\"::tag, \"msg_type\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$instrument$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$message$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" }
     ]
    },
    {
     "expression": "($A + $B * 5 + $C) * $D - ($E * $D + ($A + $B + $C))",
     "type": "math"
    },
    {
     "expression": "($A + $B * 10 + $C) * $D - ($E * $D + ($A + $B + $C))",
     "type": "math"
    },
    {
     "expression": "($A + $B * 50 + $C) * $D - ($E * $D + ($A + $B + $C))",
     "type": "math"
    },
    {
     "expression": "($A + $B * 100 + $C) * $D - ($E * $D + ($A + $B + $C))",
     "type": "math"
    }
   ]
  },
  {
   "title": "(Actual subscribe count) Trade Coalescing Latency Savings Ns",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_exchange $tag_instrument msg=$tag_msg_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" }
     ],
     "measurement": "udp_pub_subscriber_count",
     "query": "SELECT max(\"avg\") FROM \"autogen\".\"udp_pub_trade_coalesce_ns\" WHERE (\"instrument\"::tag =~ /^$instrument$/ AND \"hostname\"::tag =~ /^$host$/ AND \"msg_type\"::tag =~ /^$message$/ AND \"exchange\"::tag =~ /^$exchange$/) AND $timeFilter GROUP BY time($interval), \"app_name\"::tag, \"exchange\"::tag, \"instrument\"::tag, \"hostname\"::tag, \"msg_type\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$instrument$/" },
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$message$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" }
     ]
    },
    {
     "expression": "($A + $B * $J + $C) * $D - ($E * $D + ($A + $B + $C))",
     "type": "math"
    }
   ]
  }
 ]
}