{
 "title": "Strategy Signals - New Symbols Only",
 "description": "New Symbols added after 11th September",
 "tags": [
  "For new Symbols added after 11th September"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Strategy",
    "query": "SHOW TAG VALUES WITH KEY = strategy"
   }
  ]
 },
 "panels": [
  {
   "title": "Valuation, BBO, and Fills",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_strategy $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"signal\") AS \"Signal\" FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Signal" ], "type": "alias" }
      ],
      [
       { "params": [ "BidSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "AskSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "bid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bid" ], "type": "alias" }
      ],
      [
       { "params": [ "ask" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Ask" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"signal\") AS \"Signal\" FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Signal" ], "type": "alias" }
      ],
      [
       { "params": [ "BidSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "AskSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "bid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bid" ], "type": "alias" }
      ],
      [
       { "params": [ "ask" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Ask" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy BUY $tag_aggressorIndicator",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "aggressorIndicator::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategyFill",
     "query": "SELECT max(\"fillPrice\") AS \"BUY\" FROM \"default_signals_retention\".\"StrategyFill\" WHERE (\"strategy\" =~ /^$Strategy$/ AND \"execside\" = 'buy') AND $timeFilter GROUP BY time($interval), \"strategy\", \"aggressorIndicator\"::tag fill(none)",
     "select": [
      [
       { "params": [ "fillPrice" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "BUY" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" },
      { "condition": "AND", "key": "execside", "operator": "=", "value": "buy" }
     ]
    },
    {
     "alias": "$tag_strategy BUY $tag_aggressorIndicator",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "aggressorIndicator::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategyFill",
     "query": "SELECT max(\"fillPrice\") AS \"BUY\" FROM \"default_signals_retention\".\"StrategyFill\" WHERE (\"strategy\" =~ /^$Strategy$/ AND \"execside\" = 'buy') AND $timeFilter GROUP BY time($interval), \"strategy\", \"aggressorIndicator\"::tag fill(none)",
     "select": [
      [
       { "params": [ "fillPrice" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "BUY" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" },
      { "condition": "AND", "key": "execside", "operator": "=", "value": "buy" }
     ]
    },
    {
     "alias": "$tag_strategy SELL $tag_aggressorIndicator",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "aggressorIndicator::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategyFill",
     "select": [
      [
       { "params": [ "fillPrice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" },
      { "condition": "AND", "key": "execside", "operator": "=", "value": "sell" }
     ]
    },
    {
     "alias": "$tag_strategy SELL $tag_aggressorIndicator",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "aggressorIndicator::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategyFill",
     "select": [
      [
       { "params": [ "fillPrice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" },
      { "condition": "AND", "key": "execside", "operator": "=", "value": "sell" }
     ]
    }
   ]
  },
  {
   "title": "PnL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "$tag_strategy PnL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"pnl\") FROM \"retain_30_days\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "pnl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy PnL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"pnl\") FROM \"retain_30_days\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "pnl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Position",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$B * $C", "type": "math" },
    { "expression": "$B1 * $C1", "type": "math" }
   ]
  },
  {
   "title": "Strategy Vol Edge Signal",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy Vol Edge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "VolEdge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy Vol Edge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "VolEdge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy BidEdge Signal",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy Bid Edge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "BidEdgeSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy Bid Edge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "BidEdgeSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy AskEdge Signal",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy Ask Edge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "AskEdgeSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy Ask Edge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "AskEdgeSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Market Safety Signal",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal18",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "MarketSafetySignal" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal18",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "MarketSafetySignal" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal0",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal0",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal0\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal0",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal0\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal1",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal1\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal1",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal1\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal2",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal2\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal2",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal2\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal3",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal3\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal3",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal3\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal4",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal4",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal4\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal4",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal4\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal5",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal5\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal5\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal6",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal6\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal6\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal7",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal7\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal7\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal8",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal8\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal8\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal9",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal9\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal9\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  }
 ]
}