{
 "title": "Strategy Signals",
 "tags": [ "cicd-managed" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Strategy",
    "query": "SHOW TAG VALUES FROM \"StrategySignal\" WITH KEY = strategy"
   }
  ]
 },
 "panels": [
  {
   "title": "Valuation, BBO, and Fills",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_strategy $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"signal\") AS \"Signal\" FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Signal" ], "type": "alias" }
      ],
      [
       { "params": [ "BidSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "BidSIgnal" ], "type": "alias" }
      ],
      [
       { "params": [ "AskSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "AskSignal" ], "type": "alias" }
      ],
      [
       { "params": [ "bid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bid" ], "type": "alias" }
      ],
      [
       { "params": [ "ask" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Ask" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" },
      { "condition": "AND", "key": "bid::field", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "ask::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "$tag_strategy $tag_execside $tag_aggressorIndicator",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "aggressorIndicator::tag" ], "type": "tag" },
      { "params": [ "execside::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategyFill",
     "query": "SELECT max(\"fillPrice\") AS \"BUY\" FROM \"default_signals_retention\".\"StrategyFill\" WHERE (\"strategy\" =~ /^$Strategy$/ AND \"execside\" = 'buy') AND $timeFilter GROUP BY time($interval), \"strategy\", \"aggressorIndicator\"::tag fill(none)",
     "select": [
      [
       { "params": [ "fillPrice" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "PnL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "$tag_strategy PnL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"pnl\") FROM \"retain_30_days\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "pnl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Position",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$B1 * $C1", "type": "math" }
   ]
  },
  {
   "title": "Valuation Zero-Based and in Bps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expression": "10000 * ($signal - $mid) / $mid",
     "type": "math"
    },
    {
     "expression": "10000 * ($bidSignal - $mid) / $mid",
     "type": "math"
    },
    {
     "expression": "10000 * ($askSignal - $mid) / $mid",
     "type": "math"
    },
    {
     "expression": "10000 * ($fillBuyAdd - $mid) / $mid",
     "type": "math"
    },
    {
     "expression": "10000 * ($fillSellAdd - $mid) / $mid",
     "type": "math"
    },
    {
     "expression": "10000 * ($fillBuyRemove - $mid) / $mid",
     "type": "math"
    },
    {
     "expression": "10000 * ($fillSellRemove - $mid) / $mid",
     "type": "math"
    }
   ]
  },
  {
   "title": "Strategy Vol Edge Signal",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy Vol Edge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "VolEdge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy BidEdge Signal",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy Bid Edge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "BidEdgeSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy AskEdge Signal",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy Ask Edge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "AskEdgeSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Mft Signal",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy Mft Signal",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "MftSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Market Safety Signal",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal18",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "MarketSafetySignal" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "DAG Start to Order Signal Generation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Avg $tag_strategy ",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "strategy::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "SignalLatencyCycles",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 3.0" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "strategy::tag", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "Max $tag_strategy",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "strategy::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "SignalLatencyCycles",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 3.0" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "strategy::tag", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "market share",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "query": "SELECT last(\"market_participation\") AS \"mkt share\" FROM \"market_share_db\" WHERE ( \"strategy\"::tag =~ /^$Strategy$/) AND $timeFilter GROUP BY time($__interval), \"strategy\"::tag fill(null)"
    }
   ]
  },
  {
   "title": "Strategy Debug Signal0",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal0",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal0\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal1",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal1\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal2",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal2\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal3",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal3\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal4",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal4",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal4\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal5",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal5\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal6",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal6\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal7",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal7\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal8",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal8\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal9",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal9\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal10",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal10\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal11",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal11\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal12",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal12\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal13",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal13\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal14",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal14\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal15",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal15\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal16",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal16\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal17",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal17\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal18",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal18\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal19",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal19\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  }
 ]
}