{
 "title": "Crypto-Account-Level-Tracking",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "level",
    "label": "Mimid Account Level",
    "query": "SHOW TAG VALUES WITH KEY IN (\"level\")"
   },
   { "name": "include", "label": "Label Start Filter" },
   {
    "name": "exclude",
    "label": "Exclude Labels",
    "query": "SHOW TAG VALUES WITH KEY = \"label\""
   },
   {
    "name": "label",
    "label": "Mimid Label",
    "query": "SHOW TAG VALUES WITH KEY = \"label\" WHERE \"level\" =~ /^$level$/ AND \"label\" =~ /^$include.*/ AND \"label\" !~ /^$exclude.*/"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Daily PnL for Selection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(last_pnl) FROM (\n  SELECT last(\"pnl\") as last_pnl\n  FROM \"default\".\"acct_lvl_daily_pnl\"\n  WHERE (\"label\" =~ /^$label$/) AND (\"level\" =~ /^$level$/)\n  AND $timeFilter\n  GROUP BY time($__interval), \"label\", \"level\" fill(none)\n) \nGROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Total Daily Trade Volume for Selection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(last_trade_vol) FROM (\nSELECT last(\"trade_vol\") as last_trade_vol\nFROM \"default\".\"acct_lvl_daily_trade_vol\"\nWHERE (\"level\" =~ /^$level$/ AND \"label\" =~ /^$label$/)\nAND $timeFilter\nGROUP BY time($__interval), \"label\", \"level\"\n)\nGROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Total Notional Risk for Selection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(last_grp_risk) FROM (\nSELECT last(\"grp_risk\") as last_grp_risk\nFROM \"default\".\"acct_lvl_grp_risk\"\nWHERE (\"level\" =~ /^$level$/ AND \"label\" =~ /^$label$/)\nAND $timeFilter\nGROUP BY time($__interval), \"label\", \"level\"\n)\nGROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Total Daily PnL for Selection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_daily_pnl",
     "query": "SELECT SUM(last_pnl) FROM (\n    SELECT last(\"pnl\") AS last_pnl \n    FROM \"default\".\"acct_lvl_daily_pnl\"\n    WHERE (\"level\" =~ /^$level$/ AND \"label\" =~ /^$label$/)\n    AND $timeFilter\n    GROUP BY time($__interval), \"label\", \"level\"\n) \nGROUP BY time($__interval)\n",
     "select": [
      [
       { "params": [ "pnl" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "label::tag", "operator": "!=", "value": "SLN--DEFI" },
      { "condition": "AND", "key": "level::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Total Daily Trade Volume for Selection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "SELECT SUM(last_trade_vol) FROM (\n    SELECT last(\"trade_vol\") AS last_trade_vol \n    FROM \"default\".\"acct_lvl_daily_trade_vol\"\n    WHERE (\"level\" =~ /^$level$/ AND \"label\" =~ /^$label$/)\n    AND $timeFilter\n    GROUP BY time($__interval), \"label\", \"level\"\n) \nGROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Total Notional Risk for Selection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "SELECT SUM(last_grp_risk) FROM (\n    SELECT last(\"grp_risk\") AS last_grp_risk \n    FROM \"default\".\"acct_lvl_grp_risk\"\n    WHERE (\"level\" =~ /^$level$/ AND \"label\" =~ /^$label$/)\n    AND $timeFilter\n    GROUP BY time($__interval), \"label\", \"level\"\n) \nGROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Daily PnL by Mimid Account Level ${level}",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_daily_pnl",
     "query": "SELECT last(\"pnl\") FROM \"default\".\"acct_lvl_daily_pnl\" \nWHERE (\"level\" =~ /^$level$/ AND \"label\"=~ /^$label$/ AND \"pnl\" != 0) \nAND $timeFilter \nGROUP BY time($__interval), \"label\", \"level\" fill(none)",
     "select": [
      [
       { "params": [ "pnl" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=~", "value": "/^$level$/" },
      { "condition": "AND", "key": "label", "operator": "=~", "value": "/^$label$/" },
      { "condition": "AND", "key": "pnl", "operator": "!=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Daily PnL by Mimid Account Level ${level}",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_daily_pnl",
     "query": "from(bucket: \"Mimid_PnLStatsTestNew\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acct_lvl_daily_pnl\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pnl\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"${level}\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)  \r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "pnl" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=~", "value": "/^$label$/" },
      { "condition": "AND", "key": "level", "operator": "=~", "value": "/^$level$/" },
      { "condition": "AND", "key": "label::tag", "operator": "=~", "value": "/^$label$/" }
     ]
    }
   ]
  },
  {
   "title": "Daily Trade Volume by Mimid Account Level ${level}",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_daily_trade_vol",
     "query": "SELECT last(\"trade_vol\") FROM \"default\".\"acct_lvl_daily_trade_vol\" WHERE (\"level\" =~ /^$level$/ AND \"label\" =~ /^$label$/ AND abs(\"trade_vol\") > 0) AND $timeFilter GROUP BY time($__interval), \"label\", \"level\" fill(none)",
     "select": [
      [
       { "params": [ "trade_vol" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=~", "value": "/^$level$/" },
      { "condition": "AND", "key": "label", "operator": "=~", "value": "/^$label$/" },
      { "condition": "AND", "key": "trade_vol::field", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Daily Trade Volume by Mimid Account Level ${level}",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 18, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_daily_trade_vol",
     "query": "from(bucket: \"Mimid_PnLStatsTestNew\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acct_lvl_daily_trade_vol\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"trade_vol\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"${level}\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)  \r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "trade_vol" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=~", "value": "/^$label$/" },
      { "condition": "AND", "key": "level", "operator": "=~", "value": "/^$level$/" },
      { "condition": "AND", "key": "label::tag", "operator": "=~", "value": "/^$label$/" }
     ]
    }
   ]
  },
  {
   "title": "Notional Risk by Mimid Account Level ${level}",
   "type": "stat",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_grp_risk",
     "query": "from(bucket: \"Mimid_PnLStatsTestNew\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acct_lvl_grp_risk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grp_risk\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"${level}\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "grp_risk" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=~", "value": "/^$level$/" },
      { "condition": "AND", "key": "label", "operator": "=~", "value": "/^$label$/" }
     ]
    }
   ]
  },
  {
   "title": "Notional Risk by Mimid Account Level ${level}",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 18, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_grp_risk",
     "query": "from(bucket: \"Mimid_PnLStatsTestNew\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acct_lvl_grp_risk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grp_risk\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"${level}\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)  \r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "grp_risk" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=~", "value": "/^$label$/" },
      { "condition": "AND", "key": "level", "operator": "=~", "value": "/^$level$/" }
     ]
    }
   ]
  },
  {
   "title": "PPM by Mimid Account Level ${level}",
   "type": "stat",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "acct_lvl_daily_pnl_trade_vol_ratio",
     "query": "from(bucket: \"Mimid_PnLStatsTestNew\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acct_lvl_grp_risk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grp_risk\")\r\n  |> filter(fn: (r) => contains(value: r[\"level\"], set: ${level:json}))\r\n  |> filter(fn: (r) => contains(value: r[\"label\"], set: ${label:json}))\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "pnl_trade_vol_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=~", "value": "/^$level$/" },
      { "condition": "AND", "key": "label", "operator": "=~", "value": "/^$label$/" }
     ]
    }
   ]
  },
  {
   "title": "PPM by Mimid Account Level ${level}",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 18, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "($A > 1000) * (1000 - $A) + $A + ($A < -1000) * (-1000 - $A)",
     "type": "math"
    }
   ]
  }
 ]
}