{
 "title": "Crypto Mimid Performance GridOL",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "SHOW TAG VALUES  WITH KEY = host"
   },
   {
    "name": "mkt_data_channel",
    "query": "SHOW TAG VALUES from PerChannelPacketCount WITH KEY = channel"
   },
   {
    "name": "MDStatChannel",
    "query": "SHOW TAG VALUES from PerMDChannel WITH KEY = channel"
   },
   {
    "name": "strat",
    "query": "SHOW TAG VALUES  WITH KEY = strat"
   },
   {
    "name": "alias",
    "query": "SHOW TAG VALUES WITH KEY = alias"
   },
   {
    "name": "threadNum",
    "label": "threadNum",
    "query": "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63"
   }
  ]
 },
 "panels": [
  {
   "title": "Internal Latency: Full Mimid Strategy",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col  $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StgyDelayFromCardReceive",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col  $tag_host $measurement",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "GridOLDagEvalCyclesThread14",
     "query": "SELECT mean(\"average\") AS \"Avg\", max(\"max\") AS \"Max\" \nFROM /^GridOLDagEvalCyclesThread($threadNum)$/ \nWHERE (\"host\" =~ /^$host$/) AND $timeFilter \nGROUP BY time($interval), \"host\", \"measurement\" fill(none)",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "NumFuncCallsToGrid $col  $tag_host $measurement",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "GridOLDagEvalCyclesThread14",
     "query": "SELECT  mean(\"count\") \nFROM /^GridOLDagCyclesThread($threadNum)$/ \nWHERE (\"host\" =~ /^$host$/) AND $timeFilter \nGROUP BY time($interval), \"host\", \"measurement\" fill(none)",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    { "expression": "$F / $D *100", "type": "math" },
    {
     "alias": "$col  $tag_host $measurement",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "GridOLDagEvalCyclesThread14",
     "query": "SELECT mean(\"count\") AS \"NumGridEvals\" \nFROM /^GridOLDagEvalCyclesThread($threadNum)$/ \nWHERE (\"host\" =~ /^$host$/) AND $timeFilter \nGROUP BY time($interval), \"host\", \"measurement\" fill(0)",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col  $tag_host $measurement",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "GridOLDagEvalCyclesThread14",
     "query": "SELECT CUMULATIVE_SUM(mean(\"count\")) AS \"NumGridEvalsCumCount\" \nFROM /^GridOLDagEvalCyclesThread($threadNum)$/ \nWHERE (\"host\" =~ /^$host$/) AND $timeFilter \nGROUP BY time($interval), \"host\", \"measurement\" fill(none)",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Internal Count: Full Mimid Strategy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col  $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StgyDelayFromCardReceive",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col  $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StgyDelayFromCardReceive",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Internal Latency: Mimid Business Cycle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NewBusCycles",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/3" ], "type": "math" },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/3" ], "type": "math" },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NewBusCycles",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/3" ], "type": "math" },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/3" ], "type": "math" },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Internal Latency: Mimid Feature Calc",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FeatureCycles",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/3" ], "type": "math" },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "/3" ], "type": "math" },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FeatureCycles",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/3" ], "type": "math" },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/3" ], "type": "math" },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "External Latency: Mimid Receive vs Exchange Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MdReceiveDelayCryptoNanos",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MdReceiveDelayCryptoNanos",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Internal Count: Mimid Business Cycle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NewBusCycles",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NewBusCycles",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Internal Count: Mimid Feature Calc",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FeatureCycles",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FeatureCycles",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Latency: Dispatch Cycle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "alias" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NetworkDispatchCycles",
     "query": "SELECT mean(\"average\") /3 FROM \"NetworkDispatchCycles\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/3" ], "type": "math" },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/3" ], "type": "math" },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "alias", "operator": "=~", "value": "/^$alias$/" }
     ]
    },
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "alias" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NetworkDispatchCycles",
     "query": "SELECT mean(\"average\") /3 FROM \"NetworkDispatchCycles\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/3" ], "type": "math" },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "/3" ], "type": "math" },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "alias", "operator": "=~", "value": "/^$alias$/" }
     ]
    }
   ]
  },
  {
   "title": "External Latency: Mimid Receive vs FH Publish",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "MdGatewayDelayCryptoNanos",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "MdGatewayDelayCryptoNanos",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Latency: MDQueueInsertion Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MdQueueInsertionCycles",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 3" ], "type": "math" },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 3" ], "type": "math" },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MdQueueInsertionCycles",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 3" ], "type": "math" },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 3" ], "type": "math" },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Count: Dispatch Cycle Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NetworkDispatchCycles",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NetworkDispatchCycles",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network: Strategy Pending Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col $host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StrategyPendingQueueSize",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col $host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StrategyPendingQueueSize",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Count: Fix Send",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FixSendTotalCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FixSendTotalCount",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Coalesced New Biz Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host - Coalesced Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CoalescedNewBusinessCalls",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host - Coalesced Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CoalescedNewBusinessCalls",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Coalescing delay until done",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_host - Delay before done",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "CoalescingDelay",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host - Delay before done",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "CoalescingDelay",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Num Updates Coalesced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host - Num coalesced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CoalescedTxnBetweeNewBusinessCalls",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host - Num coalesced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "CoalescedTxnBetweeNewBusinessCalls",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Tick to Trade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col $tag_host - Tick To Trade",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TickToTrade",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col $tag_host - Tick To Trade",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "TickToTrade",
     "select": [
      [
       { "params": [ "average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Coalescing Delay Count Product",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_host - Delay before done",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "CoalescingDelay",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host - Num updates coalesced",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "CoalescedTxnBetweeNewBusinessCalls",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    { "expression": "$A * $B", "type": "math" }
   ]
  }
 ]
}