{
 "title": "drop_copy_no_trades",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_id",
    "query": "SELECT DISTINCT account_id FROM dropcopy_assets WHERE date = CURDATE();"
   },
   {
    "name": "trade_filter_assets",
    "query": "SELECT DISTINCT symbol FROM dropcopy_trades WHERE account_id IN (${account_id:sqlstring}) AND $__timeFilter(datetime);"
   }
  ]
 },
 "panels": [
  {
   "title": "Assets table for selected account",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    dca.timestamp AS \"time\",\n    dca.account_id,\n    dca.bucket,\n    dca.asset,\n    dca.status,\n    dca.total,\n    dca.available_for_trading,\n    dca.free,\n    dca.locked,\n    dca.borrowed,\n    dca.interest,\n    dca.total_usd,\n    dca.available_for_trading_usd,\n    dca.unrealized_profit,\n    dca.maintenance_margin\nFROM \n    sln_dropcopy.dropcopy_assets dca\nINNER JOIN (\n    SELECT \n        asset, \n        account_id, \n        bucket, \n        MAX(timestamp) AS max_timestamp\n    FROM \n        sln_dropcopy.dropcopy_assets\n    WHERE \n        account_id IN (${account_id:sqlstring}) AND $__timeFilter(datetime)\n    GROUP BY \n        asset, account_id, bucket\n) AS recent ON dca.asset = recent.asset \n    AND dca.account_id = recent.account_id \n    AND dca.bucket = recent.bucket \n    AND dca.timestamp = recent.max_timestamp\nLIMIT 50000;\n"
    }
   ]
  },
  {
   "title": "Minutes Since Last update",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    account_id, \n    account_name, \n    exchange_name, \n    datetime,\n    TIMESTAMPDIFF(\n        MINUTE, \n        FROM_UNIXTIME(MAX(timestamp) / 1000), \n        NOW()\n    ) AS \"minutes_since_last_update\"\nFROM sln_dropcopy.dropcopy_accounts\nWHERE account_id IN (${account_id:sqlstring})    AND $__timeFilter(datetime)\nGROUP BY account_id, account_name, exchange_name\nORDER BY account_id;\n"
    }
   ]
  },
  {
   "title": "net_usd_value of selected account",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    net_value AS \"net_value_usd\", \n    datetime AS \"time\", \n    `date`,\n    account_id, \n    account_name, \n    exchange_name, \n    currency\nFROM \n    sln_dropcopy.dropcopy_accounts \nWHERE \n    account_id IN (${account_id:sqlstring})\n    AND `date` BETWEEN DATE(FROM_UNIXTIME(${__from}/1000)) AND DATE(FROM_UNIXTIME(${__to}/1000))\n    AND $__timeFilter(datetime)\nLIMIT 1000\n"
    }
   ]
  },
  {
   "title": "Position (quantity_notional)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \n    quantity_notional AS \"value\", \n    datetime AS \"time\",\n    `date`,\n    selini_symbol, \n    account_id\nFROM \n    sln_dropcopy.dropcopy_positions \nWHERE\n    account_id IN (${account_id:sqlstring})\n    AND `date` BETWEEN DATE(FROM_UNIXTIME(${__from}/1000)) AND DATE(FROM_UNIXTIME(${__to}/1000))\n    AND $__timeFilter(datetime)\nLIMIT 2000\n"
    }
   ]
  },
  {
   "title": "asset_balance (total_usd)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT \n    total_usd AS \"total_usd\", \n    datetime AS \"time\",\n    `date`,\n    asset, \n    account_id, \n    bucket\nFROM \n    sln_dropcopy.dropcopy_assets \nWHERE\n    account_id IN (${account_id:sqlstring})\n    AND `date` BETWEEN DATE(FROM_UNIXTIME(${__from}/1000)) AND DATE(FROM_UNIXTIME(${__to}/1000))\n    AND $__timeFilter(datetime)\nLIMIT 1000\n"
    }
   ]
  }
 ]
}