{
 "title": "OG Metrics - og-stats.selini.tech",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "OG Name",
    "query": "SHOW TAG VALUES ON \"omnia_stats\" FROM \"curl_running_handle_count\" WITH KEY=\"app_name\""
   },
   {
    "name": "msg_type",
    "label": "Message",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"og_full_cycle_ns\" WITH KEY=\"msg_type\" WHERE \"app_name\" = $app_name"
   },
   {
    "name": "instr_name",
    "label": "Instrument",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"og_http_request_to_response_ns\" WITH KEY=\"instr_name\" WHERE \"app_name\" = $app_name"
   },
   {
    "name": "field",
    "label": "Data Field",
    "query": "SHOW FIELD KEYS ON \"omnia_stats\" FROM \"og_recv_to_og_request_ns\""
   },
   { "name": "aggregation", "label": "Interval Aggregation", "query": "min,mean,max" },
   {
    "name": "set_interval",
    "label": "Set Interval",
    "query": "1s,5s,10s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "OG Recv to Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "og_recv_to_og_request_ns",
     "query": "SELECT \"$aggregation\"(\"$field\") FROM \"autogen\".\"og_recv_to_og_request_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"msg_type\"::tag fill(none)",
     "select": [
      [
       { "params": [ "$field" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" }
     ]
    }
   ]
  },
  {
   "title": "Selini to Exchange Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "connection::tag" ], "type": "tag" }
     ],
     "measurement": "selini_to_exchange_order_latency_ns",
     "query": "SELECT max(\"$field\") FROM \"autogen\".\"selini_to_exchange_order_latency_ns\" WHERE $timeFilter GROUP BY time($__interval), \"connection\"::tag",
     "select": [
      [
       { "params": [ "$field" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "REST send",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rest_write_ns",
     "query": "SELECT \"$aggregation\"(\"$field\") FROM \"autogen\".\"og_recv_to_og_request_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"msg_type\"::tag fill(none)",
     "select": [
      [
       { "params": [ "$field" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" }
     ]
    }
   ]
  },
  {
   "title": "Send Order Queueing Latency (Tao -> OG Recv)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tao_create_to_og_recv_ns",
     "query": "SELECT \"$aggregation\"(\"$field\") FROM \"autogen\".\"tao_create_to_og_recv_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"msg_type\"::tag fill(none)",
     "select": [
      [
       { "params": [ "$field" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" }
     ]
    }
   ]
  },
  {
   "title": "OG Async Request Time (libcurl)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "async_request_ns",
     "query": "SELECT \"$aggregation\"(\"$field\") FROM \"autogen\".\"async_request_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"msg_type\"::tag fill(none)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "OG Async Rest Engine Service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "async_rest_engine_service_ns",
     "query": "SELECT \"$aggregation\"(\"$field\") FROM \"autogen\".\"async_rest_engine_service_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"msg_type\"::tag fill(none)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "OG Async Request Setup",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "async_request_setup_ns",
     "query": "SELECT \"$aggregation\"(\"$field\") FROM \"autogen\".\"async_request_setup_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"msg_type\"::tag fill(none)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "OG Msg Count (per second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "og_recv_to_og_request_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" }
     ]
    }
   ]
  },
  {
   "title": "OG Total Msg Count (per second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "og_recv_to_og_request_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "OG Signing Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "og_signing_ns",
     "query": "SELECT \"$aggregation\"(\"$field\") FROM \"autogen\".\"og_signing_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "OG HTTP Roundtrip Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_msg_type ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "og_http_request_to_response_ns",
     "query": "SELECT \"$aggregation\"(\"$field\") FROM \"autogen\".\"og_http_request_to_response_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instr_name\"::tag =~ /^$instr_name$/) AND $timeFilter GROUP BY time($set_interval), \"app_name\"::tag, \"msg_type\"::tag fill(none)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "instr_name::tag", "operator": "=~", "value": "/^$instr_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Exchange to OG receive time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name $tag_msg_type ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "exch_to_og_recv_time",
     "query": "SELECT \"$aggregation\"(\"$field\") FROM \"autogen\".\"og_http_request_to_response_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instr_name\"::tag =~ /^$instr_name$/) AND $timeFilter GROUP BY time($set_interval), \"app_name\"::tag, \"msg_type\"::tag fill(none)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "instr_name::tag", "operator": "=~", "value": "/^$instr_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Curl Multi-Perform Latency NOTE: This and all panels below this one are just max-max cos I cba to change - LS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "curl_multi_perform_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Curl Multi-Info Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "curl_multi_info_read_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Curl Multi-Remove Handle Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "curl_multi_remove_handle_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Curl Callback Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "curl_callback_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Curl Callback Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "curl_callback_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Curl Running Handle Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "curl_running_handle_count",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Async Service Loop Retry Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "async_service_loop_count",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "OG process_once",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "og_process_once",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "OG check_ws_engine",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "og_check_ws_engine",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "OG pop_and_perform",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 210 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "og_pop_and_perform",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "OG timer latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "timer_latency",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "(Fast Libcurl) uv_run",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "og_uv_run_time",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "(Fast Libcurl) Curl Perform",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 240 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "curl_perform_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "(Fast Libcurl) On Timeout",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 250 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "on_timeout_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "(Fast Libcurl) Start Timeout",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "start_timeout_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "(Fast Libcurl) Handle Socket",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 270 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "handle_socket",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "(Fast Libcurl) Curl Check Multi Info",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 280 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "curl_check_multi_info_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "(Fast Libcurl) curl_multi_socket_action",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 290 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_app_name ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "multi_socket_action_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  },
  {
   "title": "(Fast Libcurl) libcurl internal metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 300 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" }
     ],
     "measurement": "curl_connect_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" }
     ],
     "measurement": "curl_appconnect_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" }
     ],
     "measurement": "curl_starttransfer_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" }
     ],
     "measurement": "curl_pretransfer_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name::tag" ], "type": "tag" }
     ],
     "measurement": "curl_total_ns",
     "query": "SELECT max(\"max\") FROM \"autogen\".\"fh_json_full_cycle_ns\" WHERE (\"app_name\"::tag =~ /^$app_name$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"msg_type\"::tag =~ /^$msg_type$/) AND $timeFilter GROUP BY time($__interval), \"app_name\"::tag, \"instrument\"::tag, \"msg_type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "app_name::tag", "operator": "=~", "value": "/^$app_name$/" }
     ]
    }
   ]
  }
 ]
}