{
 "title": "Production Crypto Trade Metrics",
 "description": "Visualization of Production Crypto Perf Counters",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES WITH KEY IN (\"hostname\",\"host\")"
   },
   {
    "name": "Symbol",
    "label": "Symbol",
    "query": "SHOW TAG VALUES WITH KEY IN (\"symbol\") WHERE \"hostname\" = '$Hostname'"
   }
  ]
 },
 "panels": [
  {
   "title": "Feed Handler Performance Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API OrderBook Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "OrderBook Count $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "orderbook_count_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Aggregated WS OnMsg Callbacks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "OnMsg CB @$tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "cb_onmsg_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Order Gateway Rest Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "$tag_app_name - $tag_msg_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "account_id" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "msg_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "order_gateway_msg_delta_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Order Gateway Rest Response Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "msg_type" ], "type": "tag" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "order_gateway_msg_delta_avg" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$Symbol$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "msg_type" ], "type": "tag" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "order_gateway_msg_delta_max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$Symbol$/" }
     ]
    }
   ]
  },
  {
   "title": "OrderBook Transaction Time Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Delta $tag_app_name.$tag_symbol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "orderbook_transact_delta_avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$Symbol$/" }
     ]
    },
    {
     "alias": "Max Delta $tag_app_name.$tag_symbol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "orderbook_transact_delta_max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$Symbol$/" }
     ]
    },
    {
     "alias": "Min Delta $tag_app_name.$tag_symbol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "orderbook_transact_delta_min" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$Symbol$/" }
     ]
    }
   ]
  },
  {
   "title": "Aggregate Trade Transaction Time Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Delta $tag_app_name.$tag_symbol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "agg_trade_transact_delta_avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$Symbol$/" }
     ]
    },
    {
     "alias": "Max Delta $tag_app_name.$tag_symbol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "agg_trade_transact_delta_max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$Symbol$/" }
     ]
    },
    {
     "alias": "Min Delta $tag_app_name.$tag_symbol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "agg_trade_transact_delta_min" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$Symbol$/" }
     ]
    }
   ]
  },
  {
   "title": "Symbol Crossed Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "Crossed Count $tag_app_name $tag_symbol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "is_crossed_count_max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "TradeStream Transaction Time Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Average Delta $tag_app_name.$tag_symbol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "trade_transact_delta_avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$Symbol$/" }
     ]
    },
    {
     "alias": "Max Delta $tag_app_name.$tag_symbol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "trade_transact_delta_max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$Symbol$/" }
     ]
    },
    {
     "alias": "Min Delta $tag_app_name.$tag_symbol",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "trade_transact_delta_min" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$Symbol$/" }
     ]
    }
   ]
  },
  {
   "title": "Loop Cycle Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "ws_engine_service $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       {
        "params": [
         "loop_ws_engine_service_cycle_times_max"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    },
    {
     "alias": "pop_and_perform $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       {
        "params": [
         "loop_post_pop_and_perform_cycle_times_max"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    },
    {
     "alias": "process_once $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       {
        "params": [
         "loop_post_process_once_cycle_times_max"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    },
    {
     "alias": "service $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       {
        "params": [
         "loop_post_service_cycle_times_max"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    },
    {
     "alias": "check_api $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       {
        "params": [
         "loop_post_check_api_cycle_times_max"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    },
    {
     "alias": "service_registered $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       {
        "params": [
         "loop_service_registered_cycle_times_max"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    },
    {
     "alias": "loop_cycle_times $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "loop_cycle_times_max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    },
    {
     "alias": "lws callback client receive max $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       {
        "params": [
         "lws_callback_client_receive_cycles_max"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    },
    {
     "alias": "lws callback decompress max $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       {
        "params": [
         "lws_callback_decompress_cycles_max"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    },
    {
     "alias": "lws event cb max $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "lws_event_cb_cycles_max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    },
    {
     "alias": "lws on message max $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "lws_on_message_cycles_max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "UDP Publisher Msg Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "alias": "UDP Msg Count $tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "select": [
      [
       { "params": [ "udp_pub_msgs_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Websocket Ranking",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "alias": "Feed: $tag_feed_type WS: $tag_websocket",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "feed_type" ], "type": "tag" },
      { "params": [ "websocket" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "perf_counters",
     "query": "SELECT last(\"websocket_rank\") FROM \"perf_counters\" WHERE (\"hostname\" =~ /^$Hostname$/ AND \"app_name\" =~ /^$Appname$/ AND \"symbol\" =~ /^$Symbol$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "websocket_rank_max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Capture Writer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Available Space",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_hostname - $tag_ring_buffer_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ring_buffer_path" ], "type": "tag" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "perf_counters",
       "select": [
        [
         { "params": [ "ring_buffer_available_min" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Queued Bytes",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 5, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_hostname - $tag_ring_buffer_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ring_buffer_path" ], "type": "tag" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "perf_counters",
       "select": [
        [
         { "params": [ "ring_buffer_queued_avg" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$Hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "CollectD Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collectd Interface Stats",
   "type": "timeseries",
   "description": "Stats from collectd",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "alias": "Interface Rx $tag_host.$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" }
     ],
     "tz": "UTC"
    },
    {
     "alias": "Interface Tx $tag_host.$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load by Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host.CPU$tag_instance Load(%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Hostname$/" }
     ],
     "tz": "UTC"
    }
   ]
  },
  {
   "title": "System Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_host Memory $tag_type_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "free" }
     ],
     "tz": "UTC"
    },
    {
     "alias": "$tag_host Memory $tag_type_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "buffered" }
     ],
     "tz": "UTC"
    },
    {
     "alias": "$tag_host Memory $tag_type_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "cached" }
     ],
     "tz": "UTC"
    }
   ]
  },
  {
   "title": "Disk Space Free",
   "type": "timeseries",
   "description": "Available Disk space on root partition",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_host Disk Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "df_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "free" }
     ],
     "tz": "UTC"
    }
   ]
  },
  {
   "title": "Time Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "NTP Time Offset $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ntpd_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "time_offset" }
     ]
    },
    {
     "alias": "Chrony Time Offset $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "chrony_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "time_offset" }
     ]
    }
   ]
  }
 ]
}