{
 "title": "Repeater Metrics - rp-stats.selini.tech",
 "tags": [ "New Dashboard for Repeaters" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Repeater Host",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"udp_publisher_delay_ns\" WITH KEY=\"hostname\""
   },
   {
    "name": "symbol",
    "label": "Symbol",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"udp_publisher_delay_ns\" WITH KEY=\"instrument\" WHERE \"hostname\" = $host"
   },
   {
    "name": "exchange",
    "label": "Source Exchange",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"udp_publisher_delay_ns\" WITH KEY=\"exchange\" WHERE \"hostname\" = $host"
   },
   {
    "name": "msg_type",
    "label": "Message",
    "query": "SHOW TAG VALUES  ON \"omnia_stats\" FROM \"udp_publisher_delay_ns\" WITH KEY=\"msg_type\" WHERE \"hostname\" = $host"
   }
  ]
 },
 "panels": [
  {
   "title": "Source Feed Stats",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" }
     ],
     "measurement": "bytes_received",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transit Delay",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "exchange::tag" ], "type": "tag" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "remote_addr::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "publish_delay_ns",
     "query": "SELECT \"max\" FROM \"autogen\".\"publish_delay_ns\" WHERE (\"hostname\"::tag =~ /^$host$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"exchange\"::tag =~ /^$exchange$/) AND $timeFilter GROUP BY \"source\"::tag, \"msg_type\"::tag, \"instrument\"::tag, \"exchange\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" }
     ]
    }
   ]
  },
  {
   "title": "UDP Publisher Delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "source::tag" ], "type": "tag" }
     ],
     "measurement": "udp_publisher_delay_ns",
     "query": "SELECT \"max\" FROM \"autogen\".\"udp_publisher_delay_ns\" WHERE (\"hostname\"::tag =~ /^$host$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"exchange\"::tag =~ /^$exchange$/) AND $timeFilter GROUP BY \"source\"::tag, \"msg_type\"::tag, \"instrument\"::tag, \"exchange\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" }
     ]
    }
   ]
  },
  {
   "title": "Republishing Delay",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname::tag" ], "type": "tag" }
     ],
     "measurement": "source_rx_delay_ns",
     "query": "SELECT \"max\" FROM \"autogen\".\"source_rx_delay_ns\" WHERE (\"hostname\"::tag =~ /^$host$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"exchange\"::tag =~ /^$exchange$/) AND $timeFilter GROUP BY \"source\"::tag, \"msg_type\"::tag, \"instrument\"::tag, \"exchange\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" }
     ]
    }
   ]
  },
  {
   "title": "Process Delay",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "measurement": "process_delay_ns",
     "query": "SELECT \"max\" FROM \"autogen\".\"process_delay_ns\" WHERE (\"hostname\"::tag =~ /^$host$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"exchange\"::tag =~ /^$exchange$/) AND $timeFilter GROUP BY \"source\"::tag, \"msg_type\"::tag, \"instrument\"::tag, \"exchange\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" }
     ]
    }
   ]
  },
  {
   "title": "wire delay",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "msg_type::tag" ], "type": "tag" },
      { "params": [ "instrument::tag" ], "type": "tag" },
      { "params": [ "exchange::tag" ], "type": "tag" }
     ],
     "measurement": "transport_latency_ns",
     "query": "SELECT \"min\" FROM \"autogen\".\"transport_latency_ns\" WHERE (\"hostname\"::tag =~ /^$host$/ AND \"msg_type\"::tag =~ /^$msg_type$/ AND \"instrument\"::tag =~ /^$symbol$/ AND \"exchange\"::tag =~ /^$exchange$/) AND $timeFilter GROUP BY \"source\"::tag, \"msg_type\"::tag, \"instrument\"::tag, \"exchange\"::tag",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "msg_type::tag", "operator": "=~", "value": "/^$msg_type$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "exchange::tag", "operator": "=~", "value": "/^$exchange$/" }
     ]
    }
   ]
  },
  {
   "title": "Sequence Gap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sequence_gap",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "hostname::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instrument::tag", "operator": "=~", "value": "/^$symbol$/" }
     ]
    }
   ]
  }
 ]
}