{
 "title": "Risk Browser",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Firm Daily PnL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exch_daily_pnl\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pnl\")  \r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> last()  \r\n  |> group(columns: [\"_measurement\", \"_field\"])\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Skyview By Exchange",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"Risk_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"skyview_by_exchange\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)  \r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Exchange Daily PnL",
   "type": "stat",
   "gridPos": { "h": 21, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exch_daily_pnl\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pnl\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Exchange Daily PnL",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exch_daily_pnl\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pnl\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)  \r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Firm Daily Volume",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exch_daily_trade_vol\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"trade_vol\")  \r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> last()  \r\n  |> group(columns: [\"_measurement\", \"_field\"])\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Firm Daily Trade Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStatsTest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"firm_daily_trade_vol\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"trade_vol\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)  \r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Exchange Daily Volume",
   "type": "stat",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exch_daily_trade_vol\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"trade_vol\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Exchange Daily Volume",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 18, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exch_daily_trade_vol\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"trade_vol\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)  \r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Firm Group Risk",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStatsTest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exch_grp_risk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grp_risk\")  \r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> last()  \r\n  |> group(columns: [\"_measurement\", \"_field\"])\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Firm Group Risk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStatsTest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"firm_grp_risk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grp_risk\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)  \r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Exchange Group Risk",
   "type": "stat",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStatsTest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exch_grp_risk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grp_risk\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Exchange Group Risk",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 18, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "from(bucket: \"Mimid_PnLStatsTest\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exch_grp_risk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grp_risk\")\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)  \r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}