{
 "title": "Strategy Signals Copy MG",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Strategy",
    "query": "SHOW TAG VALUES WITH KEY = strategy"
   }
  ]
 },
 "panels": [
  {
   "title": "Valuation, BBO, and Fills",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_strategy $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Signal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "BidSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "BidSignal" ], "type": "alias" }
      ],
      [
       { "params": [ "AskSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "AskSignal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "BidSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "BidSignal" ], "type": "alias" }
      ],
      [
       { "params": [ "AskSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "AskSignal" ], "type": "alias" }
      ],
      [
       { "params": [ "signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "AskSignal" ], "type": "alias" }
      ],
      [
       { "params": [ "bid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "bid" ], "type": "alias" }
      ],
      [
       { "params": [ "ask" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ask" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "bid" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "Bid" ], "type": "alias" }
      ],
      [
       { "params": [ "ask" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       { "params": [ "Ask" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy BUY $tag_aggressorIndicator",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "aggressorIndicator::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategyFill",
     "select": [
      [
       { "params": [ "fillPrice" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "BUY" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" },
      { "condition": "AND", "key": "execside", "operator": "=", "value": "buy" }
     ]
    },
    {
     "alias": "$tag_strategy $tag_execside $tag_aggressorIndicator",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "aggressorIndicator::tag" ], "type": "tag" },
      { "params": [ "execside::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategyFill",
     "select": [
      [
       { "params": [ "fillPrice" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy SELL $tag_aggressorIndicator",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "aggressorIndicator::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategyFill",
     "select": [
      [
       { "params": [ "fillPrice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" },
      { "condition": "AND", "key": "execside", "operator": "=", "value": "sell" }
     ]
    },
    {
     "alias": "$tag_strategy BuyOrder",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategyOrder",
     "query": "SELECT mean(\"price\") FROM \"StrategyOrder\" WHERE (\"side\" = 'buy' AND \"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "side", "operator": "=", "value": "buy" },
      { "condition": "AND", "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy BuyOrder",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategyOrder",
     "query": "SELECT mean(\"price\") FROM \"StrategyOrder\" WHERE (\"side\" = 'buy' AND \"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "side", "operator": "=", "value": "buy" },
      { "condition": "AND", "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy SellOrder",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategyOrder",
     "query": "SELECT mean(\"price\") FROM \"StrategyOrder\" WHERE (\"side\" = 'buy' AND \"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "side", "operator": "=", "value": "sell" },
      { "condition": "AND", "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy SellOrder",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategyOrder",
     "query": "SELECT mean(\"price\") FROM \"StrategyOrder\" WHERE (\"side\" = 'buy' AND \"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "side", "operator": "=", "value": "sell" },
      { "condition": "AND", "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "PnL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "$tag_strategy PnL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"pnl\") FROM \"retain_30_days\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "pnl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy PnL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"pnl\") FROM \"retain_30_days\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "pnl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Position",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$B * $C", "type": "math" },
    { "expression": "$B1 * $C1", "type": "math" }
   ]
  },
  {
   "title": "Strategy Vol Edge Signal",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy Vol Edge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "VolEdge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy Vol Edge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "VolEdge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Market Safety Signal",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal18",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal18" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal18",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal18" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal0",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal0",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal0",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal1",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal1",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal2",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal2",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal3",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal3",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal4",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal4",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal4",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal5",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal6",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal7",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal8",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal9",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  }
 ]
}