{
 "title": "Strategy Signals Grid OL (Hedge)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Strategy",
    "query": "SHOW TAG VALUES WITH KEY = strategy"
   }
  ]
 },
 "panels": [
  {
   "title": "MoveFeature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"BidEdgeSignal\") AS \"LongTau\", mean(\"AskEdgeSignal\") AS \"ShortTau\" FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "BidEdgeSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "LongTau" ], "type": "alias" }
      ],
      [
       { "params": [ "AskEdgeSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ShortTau" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "GlobalRisk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal0\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Global" ], "type": "alias" }
      ],
      [
       { "params": [ "DebugSignal1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Local" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "HedgeAction",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy Vol Edge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "VolEdge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy Vol Edge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "VolEdge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Valuation, BBO, and Fills",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_strategy $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"signal\") AS \"Signal\" FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Signal" ], "type": "alias" }
      ],
      [
       { "params": [ "BidSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "BidSIgnal" ], "type": "alias" }
      ],
      [
       { "params": [ "AskSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "AskSignal" ], "type": "alias" }
      ],
      [
       { "params": [ "bid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bid" ], "type": "alias" }
      ],
      [
       { "params": [ "ask" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Ask" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" },
      { "condition": "AND", "key": "bid::field", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "ask::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "$tag_strategy $tag_execside $tag_aggressorIndicator",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "aggressorIndicator::tag" ], "type": "tag" },
      { "params": [ "execside::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategyFill",
     "query": "SELECT max(\"fillPrice\") AS \"BUY\" FROM \"default_signals_retention\".\"StrategyFill\" WHERE (\"strategy\" =~ /^$Strategy$/ AND \"execside\" = 'buy') AND $timeFilter GROUP BY time($interval), \"strategy\", \"aggressorIndicator\"::tag fill(none)",
     "select": [
      [
       { "params": [ "fillPrice" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "PnL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "$tag_strategy PnL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"pnl\") FROM \"retain_30_days\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "pnl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy PnL",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"pnl\") FROM \"retain_30_days\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "pnl" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Valuation Zero-Based and in Bps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expression": "10000 * ($signal - $mid) / $mid",
     "type": "math"
    },
    {
     "expression": "10000 * ($bidSignal - $bid) / $mid",
     "type": "math"
    },
    {
     "expression": "10000 * ($askSignal - $ask) / $mid",
     "type": "math"
    },
    { "expression": "$mid-$mid", "type": "math" },
    {
     "expression": "10000 * ($fillBuyAdd - $mid) / $mid",
     "type": "math"
    },
    {
     "expression": "10000 * ($fillSellAdd - $mid) / $mid",
     "type": "math"
    },
    {
     "expression": "10000 * ($fillBuyRemove - $mid) / $mid",
     "type": "math"
    },
    {
     "expression": "10000 * ($fillSellRemove - $mid) / $mid",
     "type": "math"
    }
   ]
  },
  {
   "title": "Position",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expression": "$B * $C", "type": "math" },
    { "expression": "$B1 * $C1", "type": "math" },
    { "expression": "$B1-$B1", "type": "math" }
   ]
  },
  {
   "title": "Grid details",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col $tag_strategy",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal8\") AS \"Top_Tuple_Bid\", mean(\"DebugSignal9\") AS \"Top_Tuple_Ask\", mean(\"DebugSignal10\") AS \"Inner Most Bid\", mean(\"DebugSignal11\") AS \"Inner Most Ask\" FROM \"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" },
       { "params": [ "Top_Tuple_Bid" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" },
      { "condition": "AND", "key": "DebugSignal8::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "$col $tag_strategy",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal8\") AS \"Top_Tuple_Bid\", mean(\"DebugSignal9\") AS \"Top_Tuple_Ask\", mean(\"DebugSignal10\") AS \"Inner Most Bid\", mean(\"DebugSignal11\") AS \"Inner Most Ask\" FROM \"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" },
       { "params": [ "Top_Tuple_Ask" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" },
      { "condition": "AND", "key": "DebugSignal9::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "$col $tag_strategy",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal8\") AS \"Top_Tuple_Bid\", mean(\"DebugSignal9\") AS \"Top_Tuple_Ask\", mean(\"DebugSignal10\") AS \"Inner Most Bid\", mean(\"DebugSignal11\") AS \"Inner Most Ask\" FROM \"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal10" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" },
       { "params": [ "Inner Most Bid" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" },
      { "condition": "AND", "key": "DebugSignal10::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "$col $tag_strategy",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal8\") AS \"Top_Tuple_Bid\", mean(\"DebugSignal9\") AS \"Top_Tuple_Ask\", mean(\"DebugSignal10\") AS \"Inner Most Bid\", mean(\"DebugSignal11\") AS \"Inner Most Ask\" FROM \"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal11" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" },
       { "params": [ "Inner Most Ask" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" },
      { "condition": "AND", "key": "DebugSignal11::field", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "$col $tag_strategy",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal8\") AS \"Top_Tuple_Bid\", mean(\"DebugSignal9\") AS \"Top_Tuple_Ask\", mean(\"DebugSignal10\") AS \"Inner Most Bid\", mean(\"DebugSignal11\") AS \"Inner Most Ask\" FROM \"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 10" ], "type": "math" },
       { "params": [ "signal" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$col $tag_strategy",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"bid\")  *10 AS \"Bid\", mean(\"ask\") *10 AS \"Ask\" FROM \"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\"::tag fill(null)",
     "select": [
      [
       { "params": [ "bid" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *10" ], "type": "math" },
       { "params": [ "Bid" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$col $tag_strategy",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal8\") AS \"Top_Tuple_Bid\", mean(\"DebugSignal9\") AS \"Top_Tuple_Ask\", mean(\"DebugSignal10\") AS \"Inner Most Bid\", mean(\"DebugSignal11\") AS \"Inner Most Ask\" FROM \"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal12" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "NthFromBid" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$col $tag_strategy",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal8\") AS \"Top_Tuple_Bid\", mean(\"DebugSignal9\") AS \"Top_Tuple_Ask\", mean(\"DebugSignal10\") AS \"Inner Most Bid\", mean(\"DebugSignal11\") AS \"Inner Most Ask\" FROM \"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal13" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "NthFromAsk" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    { "expression": "($E /$F - 1 )* 10000", "type": "math" }
   ]
  },
  {
   "title": "Strategy Mft Signal",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy Mft Signal",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "MftSignal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Market Safety Signal",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal18",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "MarketSafetySignal" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal18",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "select": [
      [
       { "params": [ "MarketSafetySignal" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "market share",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "query": "SELECT last(\"market_participation\") AS \"mkt share\" FROM \"market_share_db\" WHERE ( \"strategy\"::tag =~ /^$Strategy$/) AND $timeFilter GROUP BY time($__interval), \"strategy\"::tag fill(null)"
    }
   ]
  },
  {
   "title": "Strategy Debug Signal2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal2",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal2\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal2",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal2\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal3",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal3",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal3\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal3",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal3\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal4",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal4",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal4\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal4",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal4\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal5",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal5\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal5\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal6",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal6\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal6\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal7",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal7\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal7\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal8",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal8\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal8\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Strategy Debug Signal9",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal9\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    },
    {
     "alias": "$tag_strategy DebugSignal5",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "strategy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StrategySignal",
     "query": "SELECT mean(\"DebugSignal9\") FROM \"default_signals_retention\".\"StrategySignal\" WHERE (\"strategy\" =~ /^$Strategy$/) AND $timeFilter GROUP BY time($interval), \"strategy\" fill(none)",
     "select": [
      [
       { "params": [ "DebugSignal9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$Strategy$/" }
     ]
    }
   ]
  }
 ]
}