{
 "title": "Breakglass get secrets",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "secret",
    "query": "SELECT secret\nFROM secret_gets_non_breakglass\nWHERE $__timeFilter(ts)\nGROUP BY secret\nORDER BY MAX(ts) DESC\nLIMIT 1000;  "
   }
  ]
 },
 "panels": [
  { "title": "Selected Secret", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Secrets called per 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST((CAST(ts AS LONG) / 300000000) * 300000000 AS TIMESTAMP) AS \"time\",  -- 5m bucket\n  secret,\n  /* Legend label: if a single secret is selected, use the variable value; else fall back to the actual secret */\n  CASE\n    WHEN '${secret:raw}' != '__all' AND '${secret:csv}' NOT LIKE '%,%' THEN '${secret:raw}'\n    ELSE secret\n  END AS series_name,\n  COUNT(*) AS gets\nFROM secret_gets_non_breakglass\nWHERE\n  ( '${secret:raw}' = '__all' OR secret IN (${secret:sqlstring}) )\n  AND CAST(ts AS LONG) BETWEEN (${__from} * 1000) AND (${__to} * 1000)  -- ms -> µs\nGROUP BY \"time\", secret, series_name\nORDER BY \"time\";\n"
    }
   ]
  },
  {
   "title": "Gets Secret per secret and region (Breakglass: No) ${secret}",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  region,\n  secret,\n  ts AS \"time\",\n  user_instance\nFROM secret_gets_non_breakglass\nWHERE\n  ( '${secret:raw}' = '__all' OR secret IN (${secret:sqlstring}) )\n  AND CAST(ts AS LONG) BETWEEN (${__from} * 1000) AND (${__to} * 1000)  -- ms → µs\nORDER BY \"time\" DESC\nLIMIT 1000;\n"
    }
   ]
  },
  { "title": "All secrets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Gets Secret per secret and region (Breakglass: No)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  secret,\n  region,\n  count(*) AS gets\nFROM secret_gets_non_breakglass\nWHERE $__timeFilter(ts)\nGROUP BY secret, region\nORDER BY gets DESC;\n"
    }
   ]
  },
  {
   "title": "Secret per user/instance with ip (Breakglass: No)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  user_instance,\n  COALESCE(NULLIF(private_ip, ''), '(none)') AS private_ip,\n  secret,\n  count() AS total_gets\nFROM secret_gets_non_breakglass\nWHERE $__timeFilter(ts)\nGROUP BY user_instance, private_ip, secret\nORDER BY total_gets DESC;\n"
    }
   ]
  }
 ]
}