{
 "title": "Chronicle Jitter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "SHOW TAG VALUES FROM \"jitter\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Chronicle Jitter (On Isolated cores only)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jitter",
     "query": "SELECT mean(\"events_per_hour\") \nFROM \"jitter\" \nWHERE $timeFilter \nGROUP BY time($__interval), \"latency_us\" \nfill(null)\n",
     "select": [
      [
       { "params": [ "events_per_hour" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chronicle Queue write-to-read latency (ns) : Message size 4096",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "percentile: $tag_percentile ",
     "query": "SELECT mean(\"latency_ns\") \nFROM \"latency_test\" \nWHERE $timeFilter AND \"message_size\" = '4096' \nGROUP BY time($__interval), \"percentile\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Chronicle Queue write-to-read latency (ns) : Message size 1024",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "percentile: $tag_percentile ",
     "query": "SELECT mean(\"latency_ns\") \nFROM \"latency_test\" \nWHERE $timeFilter AND \"message_size\" = '1024' \nGROUP BY time($__interval), \"percentile\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Chronicle Queue write-to-read latency (ns) : Message size 512",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "alias": "percentile: $tag_percentile ",
     "query": "SELECT mean(\"latency_ns\") \nFROM \"latency_test\" \nWHERE $timeFilter AND \"message_size\" = '512' \nGROUP BY time($__interval), \"percentile\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Chronicle Queue write-to-read latency (ns) : Message size 256",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "alias": "percentile: $tag_percentile ",
     "query": "SELECT mean(\"latency_ns\") \nFROM \"latency_test\" \nWHERE $timeFilter AND \"message_size\" = '256' \nGROUP BY time($__interval), \"percentile\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Chronicle Queue write-to-read latency (ns) : Message size 64",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "alias": "percentile: $tag_percentile ",
     "query": "SELECT mean(\"latency_ns\") \nFROM \"latency_test\" \nWHERE $timeFilter AND \"message_size\" = '64' \nGROUP BY time($__interval), \"percentile\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Chronicle Queue write-to-read latency (ns) : Message size 8",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "alias": "percentile: $tag_percentile ",
     "query": "SELECT mean(\"latency_ns\") \nFROM \"latency_test\" \nWHERE $timeFilter AND \"message_size\" = '8' \nGROUP BY time($__interval), \"percentile\" fill(null)\n"
    }
   ]
  }
 ]
}